### ISSUE TITLE
Port constant isn't used when it counts

### ISSUE THREAD

**Issue by donno** [drone/drone-ui#103]
In webpack.devserver.js, there is a constant defined for the port the server will listen on.

However at the end of the file, instead of listening on this port, has the literal 9000 instead and then falsely claims to be listening on the port specified by the constant.
```
server.listen(9000, (err) => {
  if (err) return console.err(err);
  console.log(`Now listening on http://localhost:${port}`);
});
```

I believe that 9000 should be changed to port and all will be good.

**Comment by bradrydzewski** [comment]
closing since `webpack.devserver.js` was removed in favor of `polymer serve`
