### ISSUE TITLE
When adding secrets in the UI for a pem style variable it doesn't use it correctly for the plugin.

### ISSUE THREAD

**Issue by josmo** [drone/drone-ui#105]
Drone version:
.6

Steps to repro:
 1. go to the secrets section and add the contents of a pem file and save.
 2. run a build

Results:
The build will fail
ie. In the SFTP plugin it will result in ssh: no key found.

Need to have an option to format correctly or have it know out to.

**Comment by bradrydzewski** [comment]
would a `<textarea>` solve this issue?

**Comment by josmo** [comment]
I'll give it a try when I'm off the boat:)
