### ISSUE TITLE
Doesn't look like drone 0.5 has a UI view of the active nodes anymore?

### ISSUE THREAD

**Issue by mhagen-vmware** [drone/drone-ui#107]
Drone 0.4 had:
https://<drone-ip>/settings/nodes

If it is in fact the case that we no longer have that page in drone 0.5, can you work to add that back please?

**Comment by tboerger** [comment]
I don't think so. The model totally changed with 0.5. You have to launch agents which are doing self-registration. So no need for this UI.

**Comment by mhagen-vmware** [comment]
Ok, but how do we get a list of which nodes are self-registered?  How do we diagnose a connectivity problem down the road?

Mainly for example, you are working along and you have a bunch of workers, some of them go down. Do we have no way of knowing now?  Suddenly our builds are all just pending assignment to workers and we don't know why?  I think it would be valuable to be able to see that information from the perspective of the server, and barring actual live status a list of workers from a centralized location would at least allow us to easily grab the list and ping the server if we suspect something is wrong.

**Comment by bradrydzewski** [comment]
@mhagen-vmware when agents were managed via drone, this was easy because it was just a database query. With this new model it just becomes more complex. It is certainly a useful feature, but there is just nobody to implement it at this time.

**Comment by bradrydzewski** [comment]
related issues to enable tracking agents https://github.com/drone/drone/issues/1989 and to expose the activate agent list at https://github.com/drone/drone/issues/1867

**Comment by ozbillwang** [comment]
I dig the problem and found we can use API to get the workers. But still can't map which workers are offline. 

Its API endpoint is `/api/info/queue`

```

{
    "pending": null,
    "running": null,
    "stats": {
        "worker_count": 3,
        "pending_count": 0,
        "running_count": 0,
        "completed_count": 0
}
```


Two of them are useful for me. I am thinking to export this as metric, so we can take care and generate alarms base on them:

        "worker_count": 3,
        "pending_count": 0,

**Comment by bradrydzewski** [comment]
> I dig the problem and found we can use API to get the number of workers. But still can't map which workers are offline.

I recommend the following:

* label your servers so you know they are agents (e.g. label in aws)
* use your cloud providers API to list agents (e.g. use your aws API to return the server list)
* login to your instance and check the agent status

It is unlikely that drone will ever manage the state of your servers. This can be done by others tools such as monitoring systems, etc. So you'll need to find a solution outside of drone for this.

**Comment by ozbillwang** [comment]
Drone agents are docker containers, I'd like to get basic information (or new feature), when agents register themselves to server, they need provide below informations to server: such as, container host name (or any other unique id), its host's instance id, its label/tag, etc.

**Comment by bradrydzewski** [comment]
> Drone agents are docker containers, I'd like to get basic information (or new feature), when agents register themselves to server, they need provide below informations to server: such as, container host name (or any other unique id), its host's instance id, its label/tag, etc.

Sorry this will not be possible. We are not planning to store agent registration in the database which means there is no reliable way to provide this information on-demand. We do plan to expose a heathcheck endpoint (in support of Docker HEALTHCHECK) which you could hook up to your monitoring service to get a list of active nodes.
