### ISSUE TITLE
drone:0.6 No log displayed when a matrix is defined

### ISSUE THREAD

**Issue by dsanader** [drone/drone-ui#114]
Hello,

The elements of the pipeline are not displayed in the build view (org/repo/x/y) and the javascript console contains the following error when a matrix contains at least two values :
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at app.js:118
```
This is happening to me since I switched from drone:0.5 to drone:0.6.

Regards.

**Comment by dsanader** [comment]
This should probably be moved to the drone repo, the API response seems wrong.
The first proc element, has no key named children, but the second one contains all of them.
```json
{
  "procs": [
    {
      "environ": {
        "VARIABLE": "one"
      }
    },
    {
      "environ": {
        "VARIABLE": "two"
      },
      "children": [
        {
          "name": "step1",
          "state": "success"
        },
        {
          "name": "step2",
          "state": "success"
        },
        {
          "name": "step1",
          "state": "success"
        },
        {
          "name": "step2",
          "state": "success"
        }
      ]
    }
  ]
}
```

**Comment by bradrydzewski** [comment]
you need to clear your browser cache, as it probably has an old version of the dist.js embedded. I am using 0.6 with matrix and streaming logs without issue.
