### ISSUE TITLE
Drone 0.6 do not display build duration

### ISSUE THREAD

**Issue by mavimo** [drone/drone-ui#115]
## Actual

Build duration is not visibile, eg:

<img width="280" alt="screen shot 2017-05-18 at 19 26 18" src="https://cloud.githubusercontent.com/assets/43941/26215260/f7fd2318-3bff-11e7-93c7-8e9bb4047400.png">

## Expected

I can see the build duration, eg:
<img width="291" alt="screen shot 2017-05-18 at 19 26 07" src="https://cloud.githubusercontent.com/assets/43941/26215242/e8a0b268-3bff-11e7-9156-8d47a6ebc6d9.png">

**Comment by bradrydzewski** [comment]
closing as resolved / merged into 0.7
