### ISSUE TITLE
Show build duration in build history (improvement of #47)

### ISSUE THREAD

**Issue by lopsch** [drone/drone-ui#121]
In #47 the build history was amended with a build timestamp. I would suggest to display both the timestamp and the build duration so that I have a nice overview of how long the builds take and it would be in line with time displays in the repo list and the build details.

It would look like moving from this:

![time_old](https://cloud.githubusercontent.com/assets/4073114/26521123/1489376e-42e1-11e7-9ed4-c085de45ce7f.png)

to:

![time_new](https://cloud.githubusercontent.com/assets/4073114/26521125/1cc23af2-42e1-11e7-891f-1a31c1b92e5f.png)

or:

![time_new_list](https://cloud.githubusercontent.com/assets/4073114/26521126/2389aa1e-42e1-11e7-9669-45b90d2a1fde.png)

If there is interest I could provide a pull request. As it would be my first one on github, maybe it is not perfect ;-).

**Comment by bradrydzewski** [comment]
fix included in https://github.com/drone/drone-ui/commit/463e52c2c4eafd77fe4156daf479f5119587d257

![screen shot 2017-09-08 at 12 24 03 am](https://user-images.githubusercontent.com/817538/30200626-9adff93c-942c-11e7-9e9a-af6f6acfc1b5.png)
