### ISSUE TITLE
Click on repo in account overview should open the repo

### ISSUE THREAD

**Issue by lopsch** [drone/drone-ui#122]
A click on a repo in the account overview should take you to the repo details (build history).

So from here:

![acount_overview](https://cloud.githubusercontent.com/assets/4073114/26521167/6c280b16-42e2-11e7-9729-6f3dae1c78c5.png)

you should get here:

![repo_details](https://cloud.githubusercontent.com/assets/4073114/26521169/7672f31a-42e2-11e7-9b2e-3c8faf222766.png)

I could provide a pull request.

**Comment by bradrydzewski** [comment]
Clicking the cog icon will take you to the repository

**Comment by lopsch** [comment]
Yes, to the settings page (which is as expected). But when I hover the repo name, the cursor changes style to pointer, which usually indicates some kind of click behavior. As far a I can see there is no such behavior at all at the moment. So I would expect to get taken to the repo overview/build history when clicking on the repo name (which the cursor indicates somehow), but I maybe totally wrong in this case ;-).

**Comment by bradrydzewski** [comment]
This page is not intended for general repository navigation, since inactive repos have no page in drone to link to yet. For repository navigation it is recommended to use the list on the left side of the home screen. This lists all active repos and clicking will take you to the repository

**Comment by lopsch** [comment]
Good point, was missing the inactive repos. Handling could be done conditionally, anyways was just a suggestion as there is no way to get directly to the repos from that screen (although links are potentially there) and you need to take the route through Menu > Dashboard and then clicking on the desired repo (3 clicks), or clicking the drone icon and then the desired repo (2 clicks), instead of 1 direct click. It would not replace the recommended use case, it would just complement it.

Can be closed :-).
