### ISSUE TITLE
Account page not accessible

### ISSUE THREAD

**Issue by stefda** [drone/drone-ui#123]
With drone 0.7 installed, I am logged in to the UI through my GitHub account. I can see all repositories as expected, everything is building correctly. However, navigating to the Account section, all I can see is Loading... both in the sidebar and the main page.

The culprit seems to be the `https://drone.mydomain.com/api/user/repos?all=true` call that errs 500 with "Error fetching repository list. sql: Scan error on column index 21: converting driver.Value type <nil> ("<nil>") to a int: invalid syntax".

What can I do to fix this?

**Comment by bradrydzewski** [comment]
please upgrade to 0.7.1

there was a migration issue in 0.7.0 that was fixed with patch https://github.com/drone/drone/commit/ee54698c62495852538c2fae729e821c1e70ecca

**Comment by stefda** [comment]
That worked nicely, thanks!
