### ISSUE TITLE
UI sticks in 'loading' when no repositories found

### ISSUE THREAD

**Issue by flaccid** [drone/drone-ui#127]
Not a huge bug, but it did mislead us. We found that the UI doesn't stop 'loading' when no repositories found. In our case it was hard to tell what the issue might be as we started with a fresh Bitbucket Server. After adding a repo, all good.

![screen shot 2017-07-06 at 3 03 45 pm](https://user-images.githubusercontent.com/131730/27896321-9f197c28-625c-11e7-9cab-ca016b713d6d.png)

**Comment by bradrydzewski** [comment]
Thanks for the report. This is fixed in the upcoming 0.8 release :)

**Comment by flaccid** [comment]
Thanks mate!
