### ISSUE TITLE
Possibility to cancel queued builds

### ISSUE THREAD

**Issue by zzhelyazkov** [drone/drone-ui#129]
It's annoying having to wait other builds to be able to cancel the builds (from UI) you want to skip, any chance we could have that implemented? :P

**Comment by bradrydzewski** [comment]
duplicate of https://github.com/drone/drone/issues/1284

**Comment by tonglil** [comment]
@bradrydzewski not to beat a dead horse, but I think this issue should be closed and #1284 re-opened (or a new issue created).

Happy to discuss more.

Just FYI this is different from https://github.com/drone/drone/issues/1980.

**Comment by ylecuyer** [comment]
Sure this issue should be considered and reopened for a quickfix
