### ISSUE TITLE
Use pure node proxy server, remove Go dependency

### ISSUE THREAD

**Issue by choffmeister** [drone/drone-ui#13]
I might be wrong here because I just took a quick look in the `server.go`, but as far as I can see, this is only a proxy to the drone backend right?

If this is correct, for easier development it would be nice, to drop the Go part from this project entirely and just use the webpack-dev-server for that. There watching, hot reloading and all the good stuff that makes JS development so quick is already solved. And proxing (as well as proxing WS) can be done with it, too.

Is this something you would want? Then I would like to create a PR for this.

**Comment by choffmeister** [comment]
Ofc I mean for development. When bundling the go server makes very much sense.

**Comment by tboerger** [comment]
:+1: some other branch got a development server configured but without proxy

**Comment by bradrydzewski** [comment]
it is like you read my mind. I added a [note](https://github.com/drone/drone-ui/tree/baobab#running) to the readme about this. I'm open to a pure-node proxy so that frontend developers can contribute to drone without requiring Go

**Comment by choffmeister** [comment]
This can be closed

**Comment by choffmeister** [comment]
Solved with https://github.com/choffmeister/drone-ui/commit/1fe7a4358c7ad711ac449d6cae55b4134bc69c61
