### ISSUE TITLE
visualize pipeline in user interface

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#130]
from https://github.com/drone/drone/issues/1857

> Currently in the Drone UI there is no information on what the pipeline looks like and why a certain step was not run within a build. This makes debugging difficult especially for users who are new to Drone.
> 
> I would like to propose that the logs contain metadata on the build itself and what is happening within it so users can diagnose their YAML files for any issues with configuration.
> 
> During the preparation for the build the agent should output metadata on what the pipeline looks like and why a certain step is not going to run. It could also potentially let the user know what secrets are present and if the image matches why it is not injected into the current build.
> 
> Within the UI you could do something like this. This would visualize the pipeline and show why certain steps are executing but others are not. Programmer art follows.

![pipeline_proposal](https://cloud.githubusercontent.com/assets/666297/20367423/3e1944a8-ac04-11e6-8682-41dabe5f8d23.png)

**Comment by bendavies** [comment]
Here is how circleci UI presents the DAG:
![image](https://user-images.githubusercontent.com/625392/63163425-3d819d80-c01d-11e9-825c-96870bafa4f9.png)

Quite nice so you can see which steps are waiting on dependancies when the build is running, which is hard to see in drone at the moment.

**Comment by tphoney** [comment]
Hey @bendavies This has been implemented in v2  of Drone. 
![image](https://user-images.githubusercontent.com/10402706/124597794-cac17b80-de5b-11eb-9bf5-9814ad1e8c14.png)
