### ISSUE TITLE
Password manager autofill issues

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#131]
moved from https://github.com/drone/drone/issues/2135

> In version 0.8 the new login form does not integrate with browser password manager. It not autocomplete user and password and, in a clean browser, does not ask for save login data.
> Tested with Chromium Versión 59.0.3071.115. With Firefox seems work well.

**Comment by bradrydzewski** [comment]
this is labeled as __help wanted__, because it is not something I'm actively working on. If you would like to see this issue resolved, please consider sending a pull request.

**Comment by jhasse** [comment]
@bradrydzewski What do you think about creating the labels "Blink" (Chromium, Chrome, Vivaldi, ...), "Gecko" (Firefox, Pale Moon, ...), "Webkit" (Safari, Epiphany, ...) and "EdgeHTML" for assigning bugs to the different browsers?

**Comment by bradrydzewski** [comment]
relevant chrome / polymer bug https://github.com/PolymerElements/iron-form/issues/197

basically browsers need to update to account for the shadow dom when detecting and auto-completing password fields.

**Comment by jhasse** [comment]
Would it be possible to use server side rendering for the login page?

**Comment by wass3r** [comment]
You could try overriding the way the element is attached to the DOM as described here: https://www.polymer-project.org/2.0/docs/devguide/dom-template#stamp-templates-in-light-dom. I did try it and it did change the way the component was rendering. The form is nested a bit so there are other parent components that *might be* "in the way". 

However, this solution would have some other, not desirable, side effects such as probably having to move the styles to a parent component (also described in that link).

**Comment by bradrydzewski** [comment]
fixed the issue with https://github.com/drone/drone-ui/commit/463e52c2c4eafd77fe4156daf479f5119587d257
