### ISSUE TITLE
Log layout issues in Safari 10

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#132]
There seem to be issues with log layout in Safari 10. Unfortunately I don't have Safari 10/11 and am therefore unable to submit a patch for this issue. Help wanted.

Screenshot from Safari (broken)

![safari](https://files.gitter.im/drone/drone/XAG4/Screen-Shot-2017-07-22-at-10.19.22-AM.png)

Screenshot from Chrome (working)

![chrome](https://files.gitter.im/drone/drone/TDwN/Screen-Shot-2017-07-22-at-11.26.55-AM.png)

cc @jmccann

**Comment by wass3r** [comment]
Submitted a fix https://github.com/drone/drone-ui/pull/133 - I've seen this type of behavior in IE before :(
