### ISSUE TITLE
Follow all logs across steps

### ISSUE THREAD

**Issue by jmccann** [drone/drone-ui#136]
Seems new UI breaks logs up.  I like it better overall.  I love how all steps show in panel on right and you click which one you want to see logs for.

One thing that was possible in old UI was to follow logs across all steps.  I would like some similar ability with new UI.

It would be nice when using follow on a step that when the step is completed to automatically go to next step and continue to follow logs for that step.  Not sure if this should be added to existing follow button or some new "Follow All" type button created for this purpose.

**Comment by bradrydzewski** [comment]
Maybe add a double-chevron button (pointing down) to indicate follow all ? These could sit next to the other buttons in the bottom right corner of the screen.

![screen shot 2017-09-08 at 12 29 52 am](https://user-images.githubusercontent.com/817538/30200707-e86fe4aa-942c-11e7-9ccc-46faad7bd1f5.png)

**Comment by ptagr** [comment]
+1
