### ISSUE TITLE
[Feature Request] Status Favicon (Building, Queued, Error, etc.)

### ISSUE THREAD

**Issue by averypfeiffer** [drone/drone-ui#138]
It would be great if the front-end could swap out the favicon to quickly show the status of a build. I have gotten into the habit of pinning the web-interface in my browser and it would be fantastic if I could quickly see when a build is running or finished.

I don't think this would be a hard change to implement. I am willing to help out on this if needed.

**Comment by bradrydzewski** [comment]
another interesting option could be using the notification api when the browser tab is inactive

**Comment by averypfeiffer** [comment]
Very much agreed. Slack notifications and plugins are helpful, but an out-of-the-box solution for simple "is it building or not" use-cases would be great.

**Comment by bradrydzewski** [comment]
cc @lnikell, updating the favicon to reflect the status of a build could be interesting. Should be relatively simple to implement, while adding a nice little improvement to the UI/UX. Thoughts?

**Comment by bradrydzewski** [comment]
implemented in rc.4
