### ISSUE TITLE
Redirect if auth needed

### ISSUE THREAD

**Issue by blakebarnett** [drone/drone-ui#139]
If a user gets directed to a URL such as `/account/<org>` without first redirecting they will get a `Loading...` message and it will hang indefinitely.  The JS console shows that the API call got a 401, it should redirect to an authentication flow when this happens.

**Comment by suihkulokki** [comment]
This is the first impression one gets from Drone CI right now. Send a pull req to project using Drone, click on the drone/pr test link and think the CI is broken because of infinite "loading..." text.

Drone looks great, once you realize need to log in to see the results.

**Comment by bradrydzewski** [comment]
@suihkulokki the behavior you are describing is for drone 0.7. The latest version, 0.8, displays a screen prompting the user to login. It is still poorly designed, but the redirect loop is gone.

**Comment by bradrydzewski** [comment]
For reference this is what the user now sees when they are not authenticated.

![screen shot 2017-09-28 at 11 29 41 am](https://user-images.githubusercontent.com/817538/30983823-637b224a-a440-11e7-8961-13f79c56bb79.png)

**Comment by suihkulokki** [comment]
Good to to know it's already fixed. Godspeed with getting 1.0 released :+1:

**Comment by tboerger** [comment]
So maybe this issue can be closed now.
