### ISSUE TITLE
Following builds doesn't work in Firefox

### ISSUE THREAD

**Issue by jhasse** [drone/drone-ui#140]
When following is enabled, it just keeps jumping to the top of the page whenever a new line is added, not the bottom. Tested in Firefox 54 and Nightly on Linux.

**Comment by vaijab** [comment]
Same issue using Chrome (Version 61.0.3163.71 (Official Build) beta (64-bit)).

**Comment by bradrydzewski** [comment]
fixed with https://github.com/drone/drone-ui/commit/463e52c2c4eafd77fe4156daf479f5119587d257
