### ISSUE TITLE
Allow *not* hiding the repository list

### ISSUE THREAD

**Issue by tonglil** [drone/drone-ui#145]
As much as I like the logs for each step being separate, the jumping back-and-forth of the left repo nav gets annoying when it hides and shows.

I just doesn't "feel right" when the "top nav bar" shifts left and right as you click between the menu and the logs.

It seems like this was done to keep the log area wide, however personally I would sacrifice the width of the log area to keep the repo list pinned on the left and preserve the ux of pre-0.8.

**Comment by bradrydzewski** [comment]
The reason I am shifting the layouts is to make room for additional information, including coverage reporting, unit test reporting, etc. In order to make room we need to shift things around. I am still playing with different layouts, but reverting to 0.7 is probably not an option (if you see all the coverage and unit test data crammed in there)

**Comment by tonglil** [comment]
That's fair, is there a screenshot you can share that shows what the coverage info/testing info would look like?

What about this idea, put the toggles for each log/coverage/etc where the repo list use to be. This would allow the top nav bar buttons to remain in the same location.

Quick image hack:
![edit](https://user-images.githubusercontent.com/3250776/29293349-cba91606-8118-11e7-8942-a69c5f464e48.png)

**Comment by bradrydzewski** [comment]
This is an alternate layout I was playing with. The drawer combines the feed and navigation menu, with the feed only displaying the most recent N builds.

The layout becomes three columns, where the center column is the build details. In this are I can now display coverage or test report totals, with the ability (in the future) to display reports in the right panel ...

![screen shot 2017-08-14 at 9 42 07 pm](https://user-images.githubusercontent.com/817538/29298986-9daeb14a-8139-11e7-8742-831e98d218c5.png)

**Comment by tonglil** [comment]
Great to see the ability to view builds by specific branches/prs/deployment events are coming.

In this case, are "secrets"/"registry"/"settings" hidden in the "overview" pane? My concern with that is it's extra clicks to tune settings + restart a job, but it's not a big concern.

As long as mode-based hiding drawers aren't in play, it's all good :)

**Comment by bradrydzewski** [comment]
> Great to see branches / prs /deployment views are coming

Yes. The hope is to quickly see the status of a branch or pull request, and to better highlight deployment events. For example, what is the status of production? Which commit was deployed and by who? Ability to rollback. etc.

> In this case, are secrets / registry / settings hidden in the overview pane

No, they will be in the left menu as well. I am considering putting all settings, secrets and registry credentials on the same screen. But either way, there will be a link in the left menu.

> As long as mode-based hiding drawers aren't in play

Yes, the left drawer would be pinned by default 😄

**Comment by tonglil** [comment]
All sounds good, closing this issue as the future looks bright.
