### ISSUE TITLE
Different color for pending jobs

### ISSUE THREAD

**Issue by metalmatze** [drone/drone-ui#162]
It's really hard to differentiate if jobs are running or pending in the UI. 
I know the icons are different, but that doesn't really help at a certain amount.
Some different color would be nice. What about making the color more light or dark?

![screenshot from 2017-09-12 15-30-58](https://user-images.githubusercontent.com/872251/30328477-c3e2536a-97cf-11e7-9e7d-263a0820cf7d.png)

**Comment by tboerger** [comment]
Or maybe grey for the pending jobs?

**Comment by mavimo** [comment]
:+1: for gray color

**Comment by bradrydzewski** [comment]
The only concern I have with gray is that we also use this for skipped steps. For example:

<img width="348" alt="screen shot 2017-09-18 at 9 47 19 am" src="https://user-images.githubusercontent.com/817538/30553557-777fd3ea-9c56-11e7-9899-280e15247eef.png">

I am not opposed to changing the color or icon. I just want to make sure that switching pending to gray doesn't cause confusion with skipped.

**Comment by metalmatze** [comment]
And that's why I proposed to decrease the opacity. But we can do either. 😊

**Comment by bradrydzewski** [comment]
yes, maybe we use the `lighten` function in less to use a lighter shade of yellow?

**Comment by metalmatze** [comment]
Yep. I'll create a PR.

**Comment by mavimo** [comment]
@bradrydzewski @metalmatze @tboerger we are already using the same color for multiple type status, we are just moving one to gray removing from yellow, actually:

Green: 
 - success

Red:
 - declined
 - failure
 - killed
 - error

Yellow:
 - blocked
 - running
 - started
 - pending

Gray:
 - skipped

after change:

Green: 
 - success

Red:
 - declined
 - failure
 - killed
 - error

Yellow:
 - blocked
 - running
 - started

Gray:
 - pending
 - skipped

BTW Personally I prefer to do not use "lighten" color (dashboard screen typically do not have good color balancing ;) )

**Comment by metalmatze** [comment]
So should I create a PR with grey then? Any consensus on this? :relaxed:

**Comment by metalmatze** [comment]
Ah! I didn't see the PR in #166 :sweat_smile: :blush:

**Comment by mavimo** [comment]
@metalmatze :)
