### ISSUE TITLE
Show author handle in list of jobs

### ISSUE THREAD

**Issue by tonglil** [drone/drone-ui#173]
Right now the list of jobs show the author's icon, but in certain contexts many users do not have icons set.

Showing their actual handle would be clarifying.

Stretch: link to their profile (this would have to consider each git integration).

**Comment by bradrydzewski** [comment]
design refresh includes these changes in 0.9 branch :)

![repository-actions 2x](https://user-images.githubusercontent.com/817538/47926374-a4aed680-de7d-11e8-8b27-f59880b3874e.png)

**Comment by bradrydzewski** [comment]
yep, the design shows the full name, but I am using the handle in the actual implementation
