### ISSUE TITLE
Auto-redirect to restarted builds

### ISSUE THREAD

**Issue by gtaylor** [drone/drone-ui#180]
Since we now create a new build number when we restart a build, the current behavior is:

1. User clicks "restart"
1. A new build is created
1. An overlay in the lower left corner appears, signifying success.

We've had a few users get confused in thinking that their build didn't actually restart. They were expecting to see the new build fire up in their current view. We could solve this by redirecting to the restarted build:

1. User clicks "restart"
1. A new build is created
1. Redirect the user to the new build

**Comment by frebib** [comment]
Countless times I have hit the 'restart' button one too many times and have accidentally queued multiple builds (which can't be cancelled). 

This would be very useful

**Comment by bradrydzewski** [comment]
fixed in 0.9 UI
