### ISSUE TITLE
Show job duration in Job List

### ISSUE THREAD

**Issue by Niondir** [drone/drone-ui#185]
When I have a look at the list of all jobs I would be interested to see how long the jobs took. Especially when waiting for the latest job to finish.

Would be awesome if you could add this information to the table.

**Comment by bradrydzewski** [comment]
The job duration is visible in the user interface. If you look at the list of jobs you will see the duration of each step.

<img width="360" alt="screen shot 2017-11-24 at 9 29 07 am" src="https://user-images.githubusercontent.com/817538/33219917-df932806-d0f9-11e7-80b3-328670a1baf5.png">

**Comment by Niondir** [comment]
I'm talking about the overview where you see all past jobs for one project.

**Comment by mavimo** [comment]
@Niondir can you post a screenshot plz?

**Comment by bradrydzewski** [comment]
We display the pipeline duration on the main build history screen.

![screen shot 2017-11-27 at 8 15 03 am](https://user-images.githubusercontent.com/817538/33276659-08aaf202-d34b-11e7-89ce-6da6bdedd8d9.png)

There are no plans to change the build history page to display all the individual steps. This will continue to require a click through. Alternatively it is possible to create and plugin your own user interface if you prefer visualizing drone builds differently.
