### ISSUE TITLE
Move the restart build button out of the hamburger menu

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#187]
moved from https://github.com/drone/drone/issues/2278

> The restart build button is in a very unintuitive location at present.
>
> Discussed on https://discourse.drone.io/t/drone-0-8-no-restart-button/908

**Comment by ylecuyer** [comment]
Meanwhile please add a fix to close the drawer so that the user won't double click the button

**Comment by bradrydzewski** [comment]
fixed in new 0.9 layout, being tracked at https://github.com/drone/drone-ui/projects/2
