### ISSUE TITLE
Wrap long :owner/:repo  names on the left sidebar

### ISSUE THREAD

**Issue by brettswift** [drone/drone-ui#189]
As per the discussion here: 

https://discourse.drone.io/t/feature-long-account-repo-names-on-sidebar/1448/3

Long names can be hidden,  making the repository unknown until you click on it and have it render on the right pane. 

Brad suggests a css only fix here.  See the discourse for an example.

**Comment by bradrydzewski** [comment]
fixed in new 0.9 layout, being tracked at https://github.com/drone/drone-ui/projects/2
