### ISSUE TITLE
show progress bar

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#19]
I'd like to show a progress bar when certain long running actions are pending, for example, syncing the repository list. I'd like to use `<ProgressBar indeterminate />` fixed at the top section of the documented (tinted green).  See https://tleunen.github.io/react-mdl/components/progress-bar/

**Comment by jhasse** [comment]
Updated link: https://react-mdl.github.io/react-mdl/components/progress-bar/
