### ISSUE TITLE
Build steps status does not auto-refresh

### ISSUE THREAD

**Issue by NaurisSadovskis** [drone/drone-ui#193]
Hi guys, apologies for opening second issue, couldn't find if this was already raised or is an issue on my end. 

I'm running Docker-in-Docker on Kubernetes using [Helm chart](https://github.com/kubernetes/charts/tree/master/incubator/drone) & latest version (0.8.4).

When inspecting a running job, UI does not auto-refresh when build steps are completed and I have to refresh page manually to see if those have been completed. Not sure if it is intended behaviour or not.

On a related note, it appears that log follow is working intermittently during the build phase (needs few refreshes to get it to 'pick up' the logs). For me logs are fully functioning after the build step has been completed. 

Apologies for opening 2nd issue - if there is something I could help with, I could try open a PR.

**Comment by bradrydzewski** [comment]
hey @NaurisSadovskis per our [issue template](https://raw.githubusercontent.com/drone/drone-ui/master/.github/issue_template.md), we we politely ask that for end-user support questions you create a thread in our [discourse](https://discourse.drone.io) forum.
