### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by CentaurWarchief** [drone/drone-ui#197]
<img width="982" alt="screen shot 2018-03-25 at 13 37 35" src="https://user-images.githubusercontent.com/967317/37877450-e8a12d20-3031-11e8-8e47-971243d83204.png">
<img width="1121" alt="screen shot 2018-03-25 at 13 40 24" src="https://user-images.githubusercontent.com/967317/37877463-1bb0ce6e-3032-11e8-944e-cc047aa2dbd1.png">

Apparently, one of the event entries happens not to have the `start_time`:
<img width="746" alt="screen shot 2018-03-25 at 13 41 42" src="https://user-images.githubusercontent.com/967317/37877474-4e33b7c0-3032-11e8-965b-278e137fc16d.png">

**Comment by bradrydzewski** [comment]
fixed in new 0.9 branch, progress being tracked at https://github.com/drone/drone-ui/projects/2
