### ISSUE TITLE
UI doesn't scale well to small screens (like phones)

### ISSUE THREAD

**Issue by frebib** [drone/drone-ui#198]
One suggested fix I have for this is simply setting `flex-direction: column` on the main body container when the page width reaches a lower-bound. A small change, but would look something like the following:

![https://i.imgur.com/ixPdxLm.png](https://i.imgur.com/ixPdxLm.png)
![https://i.imgur.com/1dXH9d8.png](https://i.imgur.com/1dXH9d8.png)

Additionally, elements like the matrix build variables should have a `min-width` set and maybe truncation with ellipsis to prevent anomalies like this:

![https://i.imgur.com/fmSOe1N.png](https://i.imgur.com/fmSOe1N.png)

One final suggestion is to collapse the left-hand sidebar, similar to how the right hand menu is treated which expands when you mouse-over or click on it.

**Comment by bradrydzewski** [comment]
closing in favor of work being done at https://github.com/drone/drone-ui/projects/2
