### ISSUE TITLE
State of hamburger / drawer menu and its items

### ISSUE THREAD

**Issue by douglasmiranda** [drone/drone-ui#204]
I'm creating this issue to keep track of the other issues related to this subject.

It looks like this menu will vanish soon, so there are already some issues and even PRs proposing/implementing features to replace it.

This menu and the behavior related to its items sometimes are confusing:

#180 
https://github.com/drone/drone/issues/2428

But it's being considered:

#187 

And there are PRs:

#188 

And some proposals are even better (in my opinion): 

#201 

And with this changes, we can move to new stuff, like the MOST WANTED deploy button, I just can't believe we don't have that button already, I didn't even care if we put right there in the drawer menu, I just want to click deploy! hahaha

#171 
#191 

So, @bradrydzewski what can we do to help those changes to get merged?

**Comment by bradrydzewski** [comment]
closing in favor of work being done at https://github.com/drone/drone-ui/projects/2
