### ISSUE TITLE
pages: build

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#211]
Implement build page design (screenshot below)

- [x] implement initial page
- [x] implement hover effects
- [ ] implement tooltips
- [x] update icons and styles to match design
- [ ] handle scenario where build does not exist
- [ ] handle scenario where build step is selected, but build is pending (no longs)
- [ ] handle scenario where build step is selected, but build is pending approval (show approve, decline button)
- [ ] implement button to follow logs
- [ ] the restart build button and cancel buttons take a few seconds to complete. Need to disable the button and show some sort of "spinner" indicating the action is in-progress
- [ ] handle situation where build has an error state (invalid yaml, etc) and no steps
- [ ] handle situation where group of steps has an error state, and no steps exist
- [ ] handle situation where individual step has an error state, and no logs exist
- [x] handle very long logs which can freeze the browser. This can be mitigated by only showing a maximum of N lines at a time (i.e. show the last 100 lines). We can then give the user an option to expand the full logs.

![build-actions 2x](https://user-images.githubusercontent.com/817538/47926843-db392100-de7e-11e8-9d08-66cdadcdca2f.png)

**Comment by bradrydzewski** [comment]
cc @lnikell

**Comment by bradrydzewski** [comment]
@Inikell there are 3 elements that we might want to consider adding to the design:

1. a group of build steps (e.g. pipeline 1) is assigned to a specific machine once the build starts. It could be helpful to show the machine name in the user interface, in case the user wants to debug the machine further. This is related to issue https://github.com/drone/drone-ui/issues/135
2. a group of build steps (e.g. pipeline 1) may execute on different architectures (linux/amd64, linux/arm, linux/arm64, windows/amd64). It could be nice to visually show this information to the end user.

**Comment by tboerger** [comment]
This mockup looks awesome!

**Comment by bradrydzewski** [comment]
@lnikell the new icons (pending and running) look great but I think we need animation. The animation (spinning and wobble animations) are an important indication to the user, and I think are good for usability.

**Comment by bradrydzewski** [comment]
also just something to think about ... the pause button needs to be at the bottom of the screen (not at the top of the logs) otherwise it becomes impossible to pause the logs since you cannot scroll up 😄 not sure what the plan was for the pause button (didn't see it in the mockups, but just wanted to provide that detail).

**Comment by bradrydzewski** [comment]
FYI to mitigate the impact of very large logs, I implemented logic to collapse the logs by default and only show the last N logs. The user has the option to click and expand all. Initial (undesigned) view looks like this:

<img width="1026" alt="screen shot 2018-11-09 at 4 15 29 pm" src="https://user-images.githubusercontent.com/817538/48305229-c3dfe080-e4db-11e8-95ae-a3acbe9b1975.png">

The final implementation that I pushed will display a max of 250 lines by default. This should be good enough for most teams, with the ability to expand and see all when necessary.

**Comment by tboerger** [comment]
Cancel button leads to a 404 error, tried it at https://cloud.drone.io/drone/hello-world/2

**Comment by proAlexandr** [comment]
Hi @bradrydzewski, I think It will be good to add a pagination to GetBuildLogs method (in API). So we will be able to fetch only last 250 lines instead of a whole log (which can be large, for example, 2 mb). What do you think about this idea and who should handle backend changes in that case?

Architecture I see:
- there is fetch api endpoint where we could have offset + limit and reverse order which will give us an ability to "show more" without knowing total count of lines.
- we could add a download button to load all logs as json file (for example, for a first time). So If someone wants to see all logs he can download a file and work with it in a text editor instead of a browser.

Are you agree with this architecture?
