### ISSUE TITLE
components: search bar 

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#214]
Implement the repository search bar

![main-search 2x](https://user-images.githubusercontent.com/817538/47929800-661e1980-de87-11e8-87d0-53bc2c4bcedf.png)

**Comment by lnikell** [comment]
@proAlexandr we made a decision that behaviour of the search bar should be the same as at Github, when you type something and click you redirected to the new page and the search bar is cleared.
So few things we should to cover with that task
- update search behaviour according to the point above
- be able to close by escape click, now escape click clean search bar input but not closing it, let's also do the same as Github. Close but not clear.
- when we use "tab" button to pick elements, we should to close search bar when we moved out from searchbar

**Comment by bradrydzewski** [comment]
search bar is awesome!  I noticed one small issue, which is when I try to filter by `drone/` the `/` is ignored. But otherwise work perfect. Love the animated expansion when you click textbox, and the overlay.

**Comment by bradrydzewski** [comment]
playing around with the search bar now!

@lnikell we may want to re-think the "add" interaction. Right now if you click an item in the search list (even if you don't click the add button) it adds the repository. This is a bit unexpected. It also behaves the same way if you click the inactive repository on the dashboard, it automatically adds even if you don't click the add button.

**Comment by bradrydzewski** [comment]
looks like once https://github.com/iFgR/vue-shortkey/pull/54 is merged it will resolve the issue I mentioned earlier. The ability to search with a slash is really important. The ability to use arrow keys is slightly less important (if you can't search, arrow keys don't matter). So in the short term you will find arrow and enter keys are disabled inside textboxes until https://github.com/iFgR/vue-shortkey/pull/54 is merged (hopefully this is ok 😄 )

**Comment by proAlexandr** [comment]
a44b8210dea23b8dd22825f811b50c7e4480c19a
Search fixes:
1) Close on blur
2) Now, '/' key working in search field
3) Clear the search input on transition (to another page)
4) Close on 'Esc'

**Comment by lnikell** [comment]
@proAlexandr looks great, just minor improvement - ability to go to the repository by pressing "enter" on the keyboard. Currently, you could search, navigate and close search bar with a keyboard, but can't go to the selected repository.

**Comment by lnikell** [comment]
Closing the issue,  it seems everything works right.
