### ISSUE TITLE
Focus state should be replaced by hover state

### ISSUE THREAD

**Issue by lnikell** [drone/drone-ui#222]
Please use for focus state the hover state, otherwise currently when you use tab to navigate across the app or click on show all repositories it looks weird.

![](http://g.recordit.co/mcamjeEPat.gif)

better to use hover effects for that 
![image](https://user-images.githubusercontent.com/2697570/48506437-b8791600-e849-11e8-9cb4-f7c406a9f677.png)

**Comment by proAlexandr** [comment]
Done it in https://github.com/drone/drone-ui/commit/95bdda4c20be089363603f84dbcf8bceb817fce8 (Sorry, I forgot to add a issue ref to a commit message)
