### ISSUE TITLE
Long step names in pipeline breaks the presentation

### ISSUE THREAD

**Issue by ogarcia** [drone/drone-ui#223]
An image explains it better than one thousand words:
![long-step-names-on-drone](https://user-images.githubusercontent.com/572924/48623549-4409b880-e9aa-11e8-9d0a-b6df01fa12fb.png)

Maybe it must adjust the step boxes or wrap content.

**Comment by proAlexandr** [comment]
Hi, I fixed it in f2cdd1a21340008a2f277ad161adcde38c2c9816
