### ISSUE TITLE
Button to jump to bottom, top of build logs, show all logs

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#224]
I have a build step with really long lines (2000+) and I miss having the buttons to jump to the top and bottom of the build logs.

I also added (for perf reasons) the ability to limit the build logs to only display the latest 250 lines. So if you have more than 250 lines you will see a button appear to show more. This button is not styled to fit the design, so was hoping the designer could take a look :)

**Comment by proAlexandr** [comment]
Hi. The "To top" arrow and design for the "show more" button implemented here: https://github.com/drone/drone-ui/commit/d4a8c666b9dcef378ae48ad4b4b4e594d284f951
