### ISSUE TITLE
Logs for pending, skipped, errored builds

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#225]
If the step is pending (has not started yet) we see an empty log section. If the build has not started, should we show the logs? or hide them? and show a message saying the build has not started yet?

If a step is skipped we show the same empty log section. In this case there will never be any logs (since it was skipped). Should we hide the logs completely and show some message that the build was skipped?

If a step is errored we need to display an error message. There are two possible UI states for a step with build errors that we need to account for:

1. error message, no logs
2. error message, with logs

I have put a placeholder for an error message, but it does not have any design that matches the overall style of the app :)

**Comment by bradrydzewski** [comment]
here are all of the different variations that could impact how we render the build page:

1. build has an error, no stages will exist. example: yaml cannot be parsed
2. stage has an error, no steps will exist.
3. stage is blocked, no steps will exist, should show user message "Pipeline is blocked pending approval" and should display an "approve" and "decline" button to individuals with write access to the repository
4. stage is declined. no steps will exist. should show a message indicating the "Pipeline approval was declined"
5. stage is skipped / canceled, no steps will exist
6. step is skipped, no logs will exist
7. step has an error, if logs are empty, display just the error
8. step has an error, if logs exist, display the error and then the logs
9. step has is pending, no logs exist yet because the job has not started.

**Comment by lnikell** [comment]
@proAlexandr Is it done and we could move it to closed?

**Comment by proAlexandr** [comment]
In most part, it's solved. Some weaknesses still exist but they can be solved in other issues.
