### ISSUE TITLE
Foreign builds in a builds feed.

### ISSUE THREAD

**Issue by proAlexandr** [drone/drone-ui#229]
Sometimes foreign builds appear in a builds feed. Because they are returned by `/api/stream` method. I think it's better to make changes in the api method than try to filter events in the frontend.

![image](https://user-images.githubusercontent.com/1674582/49219871-e4150800-f3d4-11e8-996f-6d6f98c88319.png) (lnilell/hello-world isn't a repo to which I have access)

**Comment by bradrydzewski** [comment]
it needs to be filtered in the frontend because the `/api/stream`. The reason is that even though `lnikell/hello-world` is not your project, you have the ability to view the page in the user interface, and therefore need to receive the live updates.

**Comment by lnikell** [comment]
The issue is closed, for now, we discussed that for 1.0.0 version we will not make changes on the backend and filtering everything on the frontend for the time being.
