### ISSUE TITLE
Log output should be 80 columns wide

### ISSUE THREAD

**Issue by jhasse** [drone/drone-ui#230]
Currently it seems to be 76 columns? This causes a line break in nearly every line for tools like DNF:

![bildschirmfoto von 2018-11-30 09-59-54](https://user-images.githubusercontent.com/80071/49279072-c902d080-f486-11e8-9ffb-39fa2bec8a72.png)

80 columns seems to be the convention for many terminal programs at which they add hard line breaks, so I think it would be a good max value for the non-fullscreen view.

**Comment by proAlexandr** [comment]
Hi @jhasse, Thank you for the proposal! I reckon it makes sense and can be useful.
@bradrydzewski What is your opinion about it? Maybe we could ask our UI designer to invent a solution?

**Comment by proAlexandr** [comment]
Hi @jhasse, @kevinsimper 
In this commit https://github.com/drone/drone-ui/commit/83e60466323189011b275a03a09ac54537d8deab I changed logs window and now it contains enough space for 80 chars. Moreover, there is a fullscreen mode. In this mode, logs take all available space in the browser's window.
<img width="679" alt="screenshot 2018-12-28 at 11 55 51" src="https://user-images.githubusercontent.com/1674582/50505864-b2f12b80-0a97-11e9-9ff5-584e80c982d0.png">

I hope It will be helpful. Let me know if you still have a problem with logs' width

**Comment by kevinsimper** [comment]
Hi @jhasse, nice with the edit 👍 😄 

I had seen the fullscreen button, the problem is that it takes an extra click and in a busy workday that is just annoying to do. I made a UserScript that does the trick and sets is to the full width. This would be the ideal as it give you a poweruser view and uses the space available while still being easy to read.

![image](https://user-images.githubusercontent.com/1126497/50511340-93550580-0a8d-11e9-9434-fda692f546c9.png)


```
// ==UserScript==
// @name Drone Full width
// @namespace Violentmonkey Scripts
// @include *://drone.*/*
// @grant GM_addStyle
// ==/UserScript==
let element;

requestAnimationFrame(check);

function check() {
  if (window.location.pathname.split("/").length > 3) {
    element =
      element ||
      GM_addStyle(`
    .container {max-width: 100%;}
    .output {width: 100% !important;}
  `);
  } else {
    if (element) {
      element.then(el => el.remove());
      element = undefined;
    }
  }
  requestAnimationFrame(check);
}
```

**Comment by lnikell** [comment]
I will close that issue, solved in the latest version.
@kevinsimper Thank you for the user script, we will discuss some customization options in future releases.

**Comment by metalmatze** [comment]
I would like to raise this issue again. I know about the fullscreen mode, but it's hard to see side navigation in fullscreen mode (you can't see it). I don't believe that most people have screens that small that we need to limit the container.
I would strongly advocate to make the container as big as possible with a bit of padding. At least make `max-width: 1200px` or something.
I don't really get the width constraint for a UX perspective here.
