### ISSUE TITLE
Trusted checkbox for repo shown for none admins

### ISSUE THREAD

**Issue by weeman1337** [drone/drone-ui#231]
**Steps to reproduce:**
- Setup drone via docker
- Login as **none admin** into the Drone UI
- Enable a repository and go to the settings

Expected:
- There shouldn't be the "trusted" checkbox for the repo

What happens:
- The "trusted" checkbox is displayed
- It can be clicked but it isn't saved

**Info:**
- drone 1.0.0-rc.1 via docker
- connected Gitea

**Comment by bradrydzewski** [comment]
I've confirmed that this is resolved [here](https://github.com/drone/drone-ui/blob/vue/src/views/Settings.vue#L10) so we can close this. This will land in rc.2
