### ISSUE TITLE
add button to link to commit

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#233]
This is a continuation of https://github.com/drone/drone-ui/issues/226. We currently have a solution in place for GitHub (which is awesome!). We need some way to link to the remote commit/tag/pr in gogs/gitea/bitbucket/stash/etc. I propose we add this as a button (below) instead of trying to squeeze into the build card.

<img width="1045" alt="screen shot 2018-12-05 at 7 50 28 pm" src="https://user-images.githubusercontent.com/817538/49704018-028fb600-fbc2-11e8-98f4-b08ae3f9f129.png">

**Comment by proAlexandr** [comment]
Hi, I did it here (https://github.com/drone/drone-ui/commit/43a04020bdc1efffcc13f4f8c8ed013f1de48fc2). Sorry, I forgot to insert a hashtag to a commit message

**Comment by bradrydzewski** [comment]
ah I see, thanks!! sorry for the false positive.
