### ISSUE TITLE
Flicker when loading the Build List / Build Item page

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#235]
It looks like "Loading ..." was added to the Build List / Build page recently.  This loading text appears and disappears almost immediately, causing a flicker. The loading text is also displayed when we have build data in the store already, and could populate the page. Ideally the loading would be displayed, but would not hide page content, if we have page content to display.

EDIT: it also looks like the dashboard has a "loading ..." message that is displayed even when the store has data that can be rendered on the page.

**Comment by proAlexandr** [comment]
Hi, @bradrydzewski 
Firstly, about Builds List page. There are two cases
1) There aren't any build in store => We should show "Loading..." text, fetch builds and show them as a list. If fetching takes a little of time there will be a flick. But without "Loading..." text there will be a flick too between a blank page and the build list. So if you would like to mitigate flick, we should use placeholders for builds cards. 
2) There are builds in store => So we have two options again
  2.1) Show them immediately => There is a possibility that a user has a slow connection so until the update is loaded he or she will see an outdated builds list
  2.2) Show "Loading..." until builds loaded. => in this case, we have the flick, but the user will be never confused by the outdated list. (I think this case is better)

About builds page. There is flickering when the user changes a step. I agreed It's a bug, I will fix it so only logs will be replaced with "Loading..." text when the user changes the step.

Finally, I have a question. Do you agree with my argumentation about Builds page (That point 2.2 is better)? If not, could you explain your vision, please? 
Thanks.

**Comment by proAlexandr** [comment]
I have fixed Build page in https://github.com/drone/drone-ui/commit/e071d33a6942fb5f5a247c0726dbfd5ce402d7cb

**Comment by lnikell** [comment]
I think the solution is implemented, closing until further notices.
