### ISSUE TITLE
[bug] slash hotkey conflict

### ISSUE THREAD

**Issue by lizheming** [drone/drone-ui#240]
When I input slash to secret input form at setting page, it always fire top search bar. I think when input is focus it shouldn't listen slash hotkey. I'm use drone 1.0.0-rc.3.

![2018-12-27 10 20 24 2018-12-27 22_27_53](https://user-images.githubusercontent.com/424491/50483435-c0220200-0a26-11e9-9889-193931825bee.gif)

**Comment by proAlexandr** [comment]
Hi @lizheming, thank you so much for the bug report. I have tried to fix it here 
8bd5532

**Comment by lizheming** [comment]
OK, thank you for your working, it looks ok for me.
