### ISSUE TITLE
Web UI throw Error when log request return null

### ISSUE THREAD

**Issue by lizheming** [drone/drone-ui#244]
Hello, I met an error when my repo build log return `null`. you can see more detail in screenshot.

![image](https://user-images.githubusercontent.com/424491/50899984-a8974000-144e-11e9-8442-d1b672e67463.png)

I found there has a similar issue in repo: https://github.com/drone/drone-ui/issues/144, but it's closed in 2 years ago so I decide to submit a new issue to report it. I think the api we request should return `[]` forever.

**Comment by proAlexandr** [comment]
Hi @lizheming, thanks a lot for the issue report, it's clear and helpful! I have fixed it in the aforementioned commit. 👍

**Comment by lizheming** [comment]
😄 np~
