### ISSUE TITLE
UI overflow in Drone 1.0.0-rc3

### ISSUE THREAD

**Issue by kolaente** [drone/drone-ui#246]
Sometimes there is an overflow of the console field in drone:
![overflow](https://user-images.githubusercontent.com/13721712/51001872-c12c5680-1531-11e9-8f2e-8f9575a76c74.png)

**Comment by proAlexandr** [comment]
Hi, @kolaente. Thank you for the bug report!
Sorry, but I can't reproduce it. Could you say your browser name and a repo name if it's public and you use cloud.drone.io?

**Comment by kolaente** [comment]
@proAlexandr I'm not using cloud.drone.io, but the build is public: https://drone1.kolaente.de/vikunja/api/30/2/4
It only happens though when a build is running, I could record a video or restart it, whats you preference?

My browser is Firefox developer edition (64bit) version 65.0b9. Haven't tested in Chrome yet.
