### ISSUE TITLE
Update the login button to match dark header

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#248]
update the login button to reflect the new dark header

<img width="309" alt="screen shot 2019-01-13 at 6 31 36 pm" src="https://user-images.githubusercontent.com/817538/51094420-945e8600-1761-11e9-8eb7-f549b3f93805.png">

**Comment by proAlexandr** [comment]
Hi @bradrydzewski, We (I and Vlad) have updated button style.
![image](https://user-images.githubusercontent.com/1674582/51528259-146aa700-1e58-11e9-95aa-6a312236ea7b.png)

**Comment by bradrydzewski** [comment]
awesome, thanks!
