### ISSUE TITLE
Syncing not displayed

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#249]
when the page is loaded, `user.syncing=true` however it does not display the syncing message. I think this might have to do with a change in the store from `store.user` to `store.user.data`.  I am investigating this now and will try to patch tonight.

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone-ui/commit/c207170858181885aa261aae6be21a3a1d60205e

**Comment by proAlexandr** [comment]
Hi @bradrydzewski.
 Sorry, but I'm not sure that `syncing` field should be stored in `user.data` object. `syncing` is metadata of a user, not his/her own data. So, my point that `syncing` should be part of `state.user`, not `state.user.data`. It should be like `dStatus` or `tokenLoading` fields. 
What do you think about a proper place of `syncing`? Thanks.

**Comment by bradrydzewski** [comment]
> syncing is metadata of a user, not his/her own data

`syncing` is an attribute of user and is stored in the database, and syncing can be triggered outside of the user interface during the backend login process.

```
type (
	// User represents a user of the system.
	User struct {
		ID        int64  `json:"id"`
		Login     string `json:"login"`
		Email     string `json:"email"`
		Machine   bool   `json:"machine"`
		Admin     bool   `json:"admin"`
		Active    bool   `json:"active"`
		Avatar    string `json:"avatar"`
		Syncing   bool   `json:"syncing"`
```

**Comment by proAlexandr** [comment]
Ok, Thank you for an explanation. I haven't known it.
