### ISSUE TITLE
Killed build use red color for icons

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#250]
need to differentiate between skipped and killed.  Right now they have the same icon and the same color, which is making them difficult to differentiate. A killed build should be red, since it is considered an error state by the system.

**Comment by bradrydzewski** [comment]
In this case I would suggest we use the unix definition of failure, which is any process that exits with a non-zero exit code. When you kill a process in unix the process returns a 137 exit code, and is considered a fail state. Drone also assigns a 137 exit code to killed pipeline and considers this a failure state. A pipeline can be killed by the user, or can be killed by the system for exceeding time or resource limits.

**Comment by donny-dont** [comment]
I also experienced a timed out error in a long running build but there isn't any sort of visual for that either which would make it more explicit.

**Comment by benzvan** [comment]
I also just experienced the "timeout looks like a failure but also like success" result. It would be cool if there was some other indication. I'd suggest a red clock for timeout failure, but that wouldn't be very accessible. Maybe a red clock with a line through it.

**Comment by bradrydzewski** [comment]
fixed by fa7a3603d454f5b0a5c3fdf8d743b9f9ad35c968
