### ISSUE TITLE
Restart button overflows

### ISSUE THREAD

**Issue by donny-dont** [drone/drone-ui#252]
![whoops](https://user-images.githubusercontent.com/666297/51337249-6fa52f80-1a3b-11e9-875f-e56052d24234.png)

It seems like the buttons are a fixed size and the icon doesn't have enough space so it goes below. This is probably a bad choice especially considering localization would change the size of the button.

**Comment by lnikell** [comment]
@donny-dont Thank you for reporting the bug. Could you please leave here your OS and Browser. Based on your screenshot it also seems some issue with the font rendering, because the text on the restart button looks thinner than at view source.
@proAlexandr Could you please take a look at that problem?

**Comment by donny-dont** [comment]
Sorry I missed this @lnikell its Windows 10 + Chrome 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)

Looking at the inspector it looked like the width and height were explicitly specified which will bite you guys if you attempt to localize the app.

**Comment by metalmatze** [comment]
Seeing the same thing on ArchLinux with Google Chrome stable.

**Comment by donny-dont** [comment]
@lnikell @proAlexandr is there any localization framework for vue that you could be using? I still have a feeling that these sorts of things are going to come up quite a bit if you throw localized strings at it.

**Comment by lnikell** [comment]
@donny-dont we will think about the way how to implement it better, for the time being, that solution was made for the reasons to keep it the same size with the cancel button and prevent flickering effect.

**Comment by lnikell** [comment]
Could you let us know if the issue still present, I mark it as closed since I can't reproduce it in the latest available build.
