### ISSUE TITLE
Show the timezone for build time

### ISSUE THREAD

**Issue by tonglil** [drone/drone-ui#258]
It would be great if Drone can show the timezone of the builds/the system it is running on when users hover over the timestamps.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/3250776/41735509-ba9a48ec-753e-11e8-83bc-c3646a16a53d.png">

In this case, I would like to see `2018-06-20 14:57 UTC`.

**Comment by lnikell** [comment]
In Drone 1.0 we changed the way of displaying build date, since Drone 1.0 officially released I'm closing this issue.
![image](https://user-images.githubusercontent.com/2697570/56455448-bcf8ac00-635e-11e9-8d8f-54c031e81222.png)

**Comment by tboerger** [comment]
He was referring to the tooltip showing the right date instead of X minutes ago. Have this been removed?
