### ISSUE TITLE
When looking at the repository index, show default branch status

### ISSUE THREAD

**Issue by krainboltgreene** [drone/drone-ui#261]
There's no way in the UI currently, as far as I can tell, to find out the latest status of the default branch.

**Comment by lnikell** [comment]
@krainboltgreene Thanks for the feedback, the issue will be addressed in v1.1 we already have plans and design for this. It will be a separate tab for looking for statuses per branches(later per deployments).

https://github.com/drone/drone-ui/projects/3#card-15480921

**Comment by krainboltgreene** [comment]
I just upgraded to 1.0.1 and I fucking love drone. Thanks so much for making this product.

**Comment by bradrydzewski** [comment]
closed by https://github.com/drone/drone-ui/commit/4e6d42e45f13db5a8ef9fdb19e2deb007ef8212c
