### ISSUE TITLE
Grey overlay after selecting repo to activate

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [drone/drone-ui#263]
**Version**: 1.0.0-rc.5
**Description**:
After selecting a repository to activate the overlay stays gray and the user must refresh the page to be able to click **Activate**
![activate](https://user-images.githubusercontent.com/7912669/53493219-82336f80-3aa3-11e9-9a4f-b3ebada631bc.png)

**Comment by lnikell** [comment]
@laszlocph @natlibfi-arlehiko Could you please check, do you have this issue with the latest Drone build? Can't reproduce it.

**Comment by xoxys** [comment]
@lnikell still exist in latest build as described in #310

**Comment by ViViDboarder** [comment]
For me it works fine in Chrome, but fails to clear in FF.

Running `drone/drone:1.6` and using Firefox 72.0.1.

**Comment by ViViDboarder** [comment]
Ok. I found a way to fix it and tested on my FF and Chrome. I'm not sure if there are other concerns as I'm not very familiar with Vue or this project's code base generally. Happy to make changes.
