### ISSUE TITLE
Maximum of ~6 tabs causes Drone UI to hang in Chrome with "Waiting for available socket..."

### ISSUE THREAD

**Issue by tizmagik** [drone/drone-ui#264]
I've noticed that if I have ~6 or so tabs open that the Drone UI no longer responds in Chrome. Typically Chrome will just hang with a status message that says "Waiting for available socket..."

![image](https://user-images.githubusercontent.com/244704/53815788-521b1f00-3f30-11e9-8058-0f1405be8cbb.png)

macOS 10.14.3
Chrome 72

I'm assuming this is due to a Chrome bug or something although I wonder if it would make sense for Drone UI to free up sockets as long as the tab is not in focus?

**Comment by bradrydzewski** [comment]
closing since 1.0 no longer uses websockets
