### ISSUE TITLE
Syncing animation not displayed on page load

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#267]
First, just wanted to say the animation sequence for syncing is AWESOME

When the user authenticates drone will synchronize the user automatically, and the `syncing` value will be set to `true` before the page is loaded. When this happens, the animation is not displayed.

Part of the issue is related to the `watch` function on the `:opened` prop is not triggered when the component is initialized: https://forum.vuejs.org/t/watchers-not-triggered-on-initialization/12475

I tried to set `immediate: true` as suggested in the above post, but `this.anim` is undefined at this stage of the component lifecycle and therefore fails. I wasn't sure how `this.anim` was getting populated so I was a bit stuck.

**Comment by bradrydzewski** [comment]
@proAlexandr I pushed a workaround here:
https://github.com/drone/drone-ui/commit/93d1b1ec697407a89b340ab0a638d61b1f019430

This seems to fix the issue but I wanted to give you a chance to review and optimize just in case there is a better fix. Thanks for everything! :)

**Comment by lnikell** [comment]
@bradrydzewski am I right that we could close it since we removed the animation and stayed with just a sync button?
