### ISSUE TITLE
Badge/indicator for cron builds

### ISSUE THREAD

**Issue by geek1011** [drone/drone-ui#268]
When cron builds are set to a frequent schedule, it becomes hard to separate the commit builds from the cron builds without looking at each commit hash. Adding some sort of indicator for cron builds would greatly improve the readability of the build list (and repo list).

**Comment by bradrydzewski** [comment]
Minor updated. The build object now has a `cron` attribute that provides the name of the cron job that launched the build. If a build was not launched by a cron job, the field will be empty. This means the backend is now providing the data required to implement this request.

**Comment by bradrydzewski** [comment]
this is now available in `:latest`

**Comment by bobemoe** [comment]
I'm trying to get the status badge for the last cron build. 

I've tried `https://drone.DOMAIN.co.uk/api/badges/USER/REPO/status.svg?event=cron` and `https://drone.DOMAIN.co.uk/api/badges/USER/REPO/status.svg?cron=CRONNAME` but it is still not selecting the correct build.
