### ISSUE TITLE
Show pull-request enabled label in secrets list

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#269]
Re-enable https://github.com/drone/drone-ui/commit/ef034580a4df597e446ba7a5a831e3a2073d062c#diff-51298e2fbc0622c453c755998ca53879L13

**Comment by lnikell** [comment]
@bradrydzewski  Is it still the issue or it's already solved, did not get it based on the description.

**Comment by bradrydzewski** [comment]
fixed in patch ce0a4ddeef655018c55e03ec079d3e70edc88f49
