### ISSUE TITLE
Css needs to be loaded online, the page opens slowly in offline state

### ISSUE THREAD

**Issue by mortemnh** [drone/drone-ui#270]
I found that the Drone 1.0.0 version of the page needs to access an external connection to download the CSS style when loading. If it is offline, it will cause the page to open very slowly.

![image](https://user-images.githubusercontent.com/18227000/55081721-58d62580-50db-11e9-9331-f5f897db0ded.png)

**Comment by lnikell** [comment]
@bradrydzewski please close it once you will generate a new version of Drone. The fix was quite small, since we have not removed using Google Fonts after we migrate for using system fonts.
