### ISSUE TITLE
Specify variables when executing a manual pipeline from the UI

### ISSUE THREAD

**Issue by allen-hsu** [drone/drone-ui#272]
Like this gitlab ci issue
https://gitlab.com/gitlab-org/gitlab-ce/issues/44059.

Let user can input specify variavble from ui. and select Specify branch.

Have any plan to do or any idea?

**Comment by tphoney** [comment]
This is available in V2 of drone, 
![image](https://user-images.githubusercontent.com/10402706/124598157-3ad00180-de5c-11eb-8d4b-56a9c81c854b.png)
Closing this issue.
