### ISSUE TITLE
Show promotion target in build activity feed

### ISSUE THREAD

**Issue by sohan** [drone/drone-ui#276]
We have a few environments we deploy to regularly, like `master`, `dev`, `staging`, and `prod`.  After we promote a build, drone does not show the target environment of the promotion in the build activity feed. As a result, it's hard to scan the build list to see which build corresponds to which target. The drone 0.8 ui showed the build target, and it seems missing from the v1 ui.

Concretely, right now the repo listing looks like:
![image](https://user-images.githubusercontent.com/911977/56614756-a2c50500-65ce-11e9-94ad-ae54c45e51b3.png)

It'd be helpful if it looked something like this instead:
![image](https://user-images.githubusercontent.com/911977/56615085-37c7fe00-65cf-11e9-9a08-6c10e1d41a3f.png)

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone-ui/commit/b4bb5da2b193538d253b58b6d548938d1de70b64
