### ISSUE TITLE
Show the sha of the commit in the activity feed when promoting a build

### ISSUE THREAD

**Issue by sohan** [drone/drone-ui#280]
In drone 0.8, when you deploy/promote a build, the build listing contains the sha of the commit that was being promoted. We used it to quickly retrieve the git history of the last promoted commit.

In drone v1, the build listing only contains the branch name. Most of the time, the branch name is just `master`, so it's not super useful by itself. Furthermore, it's pretty difficult to find the sha of the promoted build at all -- we have to parse the output of the `clone` build step.

Can we include the git sha of the commit in the activity feed for promoted builds, or otherwise display the commit sha?

**Comment by bradrydzewski** [comment]
@lnikell we currently use a shared component for the build list and for the build details page. I wonder if it is time we break this out into a separate component so we can provide more details that may not make sense in the list. For example, and expand button to view the full commit message (similar to the ellipsis in github, etc).

**Comment by bradrydzewski** [comment]
fixed by patch https://github.com/drone/drone-ui/commit/b4bb5da2b193538d253b58b6d548938d1de70b64
