### ISSUE TITLE
Dropdown arrow is missing for settings select

### ISSUE THREAD

**Issue by lnikell** [drone/drone-ui#283]
In select component settings background, property with svg image stopped to work. 

```
background: #fff
    url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100'><polygon fill='#98a1ab' points='0,30 100, 30 50,90'/></svg>")
    no-repeat center right 10px;
```

It resulted in missing arrow in the select component.

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone-ui/commit/01fe10be3f3d8595be906f91af5901f3a83b516a
