### ISSUE TITLE
Bogus Elapsed Time on `.drone.yml` syntax errors

### ISSUE THREAD

**Issue by hughsw** [drone/drone-ui#284]
We’ve upgraded to latest Drone from 0.7.x – Bravo!

Minor bug: Devs who push commits on branches that have not yet merged our new .drone.yml file get a failed Activity due to what are now syntax errors in the old version of the file. Fair enough.

But, the elapsed time reported in the UI is bogus, `430454` hours. It looks like the elapsed time is measured from January 1, 1970.  This suggests that some part of the activity-timer is not initialized early enough in the process...

![image](https://user-images.githubusercontent.com/6404010/56869776-bfd84a00-69b9-11e9-9de8-2853df3c461d.png)

**Comment by bradrydzewski** [comment]
fixed by e6e1fcf62a1547ec7c159e225e597b96cd94d3a7 will be included in 1.5 release.
