### ISSUE TITLE
Misleading icons saying a build was broken/canceled while still running

### ISSUE THREAD

**Issue by strk** [drone/drone-ui#286]
This build: https://dronie.osgeo.org/postgis/postgis/255/1/2
Showed error message:
```
g-9.5: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

And turned all matrix entry icons to red (top-level) and gray (inner steps)
but the build continued.

This is a just-upgraded Drone-1.1 version

**Comment by bradrydzewski** [comment]
This behavior is expected, at least from a user-interface perspective. The pipeline failed and no steps were executed. They were skipped.

**Comment by strk** [comment]
Ok now that the build completed I don't see the build logs anymore, but I swear I saw the build running for pg-9.5. Now I'm puzzled about whether or not I saw what I saw. @robe can you help here ?

@bradrydzewski do you have any idea of what could be wrong with that docker ? We think to have a single agent so don't see why one of the builds would work while the other 2 would not. If we had more info about the agents it'd be easier to debug (see https://github.com/drone/drone-ui/issues/286)

**Comment by bradrydzewski** [comment]
we have a thread that suggests some steps you can take https://discourse.drone.io/t/cannot-connect-to-the-docker-daemon-at-unix-var-run-docker-sock-is-the-docker-daemon-running/4071

**Comment by strk** [comment]
Ok it looks like it was a missing `DRONE_AGENTS_ENABLED=true` variable, thanks for the support.
Shall I see again that weird icon will look closer to see if there was really a misleading behaviour (as I'm not sure anymore now)
