### ISSUE TITLE
No info shown when promoting a tag build

### ISSUE THREAD

**Issue by Fadelis** [drone/drone-ui#291]
When promoting a build from a tag event, in the ui there is no info shown about the tag:
![Unnamed](https://user-images.githubusercontent.com/6364106/58482085-01e1e080-815e-11e9-9ca8-cb6b64ea3290.png)

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone-ui/commit/b4bb5da2b193538d253b58b6d548938d1de70b64
