### ISSUE TITLE
No logs when any current stage

### ISSUE THREAD

**Issue by TheYkk** [drone/drone-ui#295]
Pass stage
![image](https://user-images.githubusercontent.com/21688838/59105663-0e73ef00-893d-11e9-8941-a13ed76efb39.png)
Current stage
![image](https://user-images.githubusercontent.com/21688838/59105657-09af3b00-893d-11e9-8942-030a39a7ed1d.png)

**Comment by BnMcG** [comment]
I seem to get a similar issue when the step in question is volume mounting the Docker socket. The repository is trusted. The Firefox console shows the following error: `invalid step argument. loadLogsForStep skipped`.

I'm running Drone 1.2 on Kubernetes 1.14 bare metal. This may be unrelated, but in this specific case the step seems to hang forever as well.

**Comment by nickbp** [comment]
Noticing a lack of log output on a Kubernetes cluster that uses containerd, with the same `loadLogsForStep` error when viewing the Drone browser UI. Drone seems to make assumptions around dockerd that are increasingly invalid on K8s clusters.

I can see the stdout logs from individual builds when viewing `kubectl logs` on the containers directly, but this isn't really feasible for users that don't have `kubectl` access. In practice all that I get from Drone is a green success or red failure indicator.

**Comment by ashwilliams1** [comment]
the issues described in this error apply to an old, deprecated kubernetes integration. If you are trying to integrate Drone with kubernetes you should be using the new kubernetes runner. Installation instructions can be found at https://kube-runner.docs.drone.io/installation/

**Comment by nickbp** [comment]
The `invalid step argument. loadLogsForStep skipped` error and hanging log fetch occurs with Drone 1.6.2 on the current Kubernetes runner.

**Comment by ashwilliams1** [comment]
The current kubernetes runner is installed using the `drone/drone-runner-kube` docker image.  Can you confirm you are using this image as opposed to the legacy runtime?  People often install the legacy kubernetes runtime as a result of using an unofficial install mechanism like helm, which is not kept up to date and defaults to deprecated features.

**Comment by wdongyu** [comment]
I have the same issues. Any workaround?

**Comment by godlzr** [comment]
Same issue here, I am using drone runner on k8s cluster. I think there is an issue with my .drone.yml, but it's hard to debug without the running log.

**Comment by andrewhowdencom** [comment]
> People often enable the legacy integration as a result of using an unofficial install mechanism like helm, which seems to default to deprecated features.

I confirm that this issue is still present in the image `drone/drone-runner-kube:1.0.0-beta.6`

**Comment by bradrydzewski** [comment]
I am unable to reproduce with drone/drone-runner-kube:1.0.0-beta.6, however, we have observed in the past that different clusters and cluster configurations can exhibit different behaviors.  For that reason, we ask the community to take an active role in helping triage issues with the Kubernetes runner while in beta, especially when we cannot reproduce. We provide a guide that you can use to get started with the codebase here:  https://discourse.drone.io/t/contributing-to-drone-for-kubernetes/3159

**Comment by andrewhowdencom** [comment]
currently pcapping the transport between `drone-kube-runner` and `drone-server` :sweat_smile: I'm inclined to think this is not a UI issue regardless as:

1. The RPCs sent by `drone-kube-runner` seem to indicate that there are no logs picked up, and 
2. The drone CLI doesn't show any logs either.

Still trying to figure out how longs get there at all currently; the issue only hits us for some build steps — more interestingly, they're even consistent build steps. Fast running ones seem to be more frequent offenders.

Will raise a note in the discourse if I figure it out.

**Comment by psych0d0g** [comment]
i occur the same phenomenon,including the `invalid step argument. loadLogsForStep skipped` browser console entry. interestingly it worked before, and stopped showing logs from the point where i restarted the whole single-node k8s cluster host.
makes me belive i had some temporary setting whatsoever in the cluster that vanished after a restart?
does that make sense?
did you ever figure out that happens @andrewhowdencom ?
![image](https://user-images.githubusercontent.com/181302/108985086-ed16e180-7690-11eb-82d7-9313694de2c3.png)

**Comment by andrewhowdencom** [comment]
... sortof. From my investigation, there's a nasty race condition in which if you `kubectl logs` too early, kubernetes returns zero length logs but no error code. Not quite sure where that is, but I wrote a retry to get around it:

— https://gist.github.com/andrewhowdencom/7ae1d52e3130c159a0031aa7f3f05a18

I haven't looked at pushing this upstream as it was a pretty dirty initial pass, and I won't have time to make it more elegant (plus i think its hard to get stuff up-streamed).
