### ISSUE TITLE
Add a new build button to the repository screen

### ISSUE THREAD

**Issue by Skaronator** [drone/drone-ui#298]
Hi,

it would be great to have a "New Build" button in the repository screen. Clicking on it should open a modal which ask for a 

- *name* of that build
- *Commit* which should be built
- *Branch* of that commit
- *Environment Variables* a text area where it should be possible to define additional env variables

Buildkite has this option and would like to see that in drone as well.

![image](https://user-images.githubusercontent.com/2886913/60582615-7295a180-9d89-11e9-81fe-c0f80aa7cc93.png)

![image](https://user-images.githubusercontent.com/2886913/60582629-7b867300-9d89-11e9-8150-78ea64e9158e.png)

**Comment by avierr** [comment]
Yeah I hate it when my build artifact upload fails due to network issues and I have no way to re-upload/re-build them.
I have to again go through a fake commit and then PR process just to make this build work again.

Stuck with Jenkins because of the above feature not being present.

**Comment by tboerger** [comment]
@avierr on network issues you can always restart a build which will launch a new build with the exact same parameters.

**Comment by stixx** [comment]
When is this feature coming on the roadmap?

**Comment by toopay** [comment]
It should be straightforward. I can start the effort if its on the owner of this repo's interest

**Comment by fabiosussetto** [comment]
I think this would be a very welcome addition, useful for a lot of people w/o too much dev effort.
I can have a look at implementing this in a PR as well, if @bradrydzewski would be up for this functionality.

**Comment by Skaronator** [comment]
This would be a really powerful feature when using over the Drone REST API. You could create your own Dashboard to trigger new builds which do whatever you want. For example a deployment on a special environment.

**Comment by Akkadius** [comment]
@toopay I look forward to it!

**Comment by shamimgeek** [comment]
This would be really great feature. expecting sooner.

**Comment by A-limon** [comment]
any update?

**Comment by toopay** [comment]
@Akkadius I haven't heard anything from the maintainer, so I reluctant to start anything.

We're actually using Spinakker atm :grinning:

**Comment by mritd** [comment]
Is there any update?

**Comment by sbussard** [comment]
This would be a really useful feature, really an expected feature to be honest. Drone is great though btw

**Comment by 0xMH** [comment]
And if possible adding a field for `event type` that will make it possible for us to change/specify the behaviour of the pipelines by handling the event they receive.

**Comment by ivmilicevic** [comment]
I see there is a open pull request ( #343 ) for this issue, will there be review and merge soon? This would really useful feature for a lot of us

**Comment by TR-SLimey** [comment]
Possible workaround for now: Navigate to your repo's webhook section and test delivery.

**Comment by darkguy2008** [comment]
2021 and no updates yet? Almost 3 years to add a feature??? (with a PR already open, BTW)...

**Comment by tphoney** [comment]
The new UI in drone V2, has this functionality now 
![image](https://user-images.githubusercontent.com/10402706/124597560-8d5cee00-de5b-11eb-8520-3ced23fc2e53.png)
Thanks for your patience.

**Comment by abdennour** [comment]
That's cool ! https://github.com/drone/drone-ui/issues/298
