### ISSUE TITLE
Use this repository as a git submodule for an update of drone-wall

### ISSUE THREAD

**Issue by maximelebastard** [drone/drone-ui#299]
Hi,

I'm working on a new version of drone/drone-wall that would be compatible with the 1.x version.

I have a pretty decent version working with React/Redux right now, but I was thinking about using this drone-ui repository as a git submodule and convert the project to Vue.

That would allow me to just use your helpers and components for the wall - which will result in an easier maintaining and less code to write on my side.

Would that be something you recommend ?

**Comment by tboerger** [comment]
Maybe it would be better to build a javascript client sdk, like drone-go which could be used by the ui and the wall project.

**Comment by bradrydzewski** [comment]
I do not recommend on using this repository as a dependency. There are no compatibility guarantees and we could choose to significantly change or break something at any time. We do have a drone-js repository which could be useful https://github.com/drone/drone-js

**Comment by maximelebastard** [comment]
Thank you for the replies.

I'll recreate my own components until a such ui library exists.
