### ISSUE TITLE
Clicking the download button to download the logs does not work in Firefox

### ISSUE THREAD

**Issue by smarter** [drone/drone-ui#300]
1. Using Firefox, go to any drone log page (e.g. https://dotty-ci.epfl.ch/lampepfl/dotty/2/1/1)
2. Click on the download icon (a cloud with an arrow)
3. Observe nothing happening (and no messages in the error console)

This issue was previously reported in the forum: https://discourse.drone.io/t/firefox-download-button-does-not-work/4730

**Comment by bobmanary** [comment]
The fix appears to be appending the link element to the DOM before triggering a blob download.

* https://github.com/drone/drone-ui/blob/vue/src/views/Build.vue#L378
* https://stackoverflow.com/a/46571691

**Comment by daxmc99** [comment]
Also looking forward to seeing this get fixed

**Comment by bradrydzewski** [comment]
We recently merged https://github.com/drone/drone-ui/pull/303 which resolves this issue.  You can upgrade to version 1.3.0 or higher to get this fix.
