### ISSUE TITLE
Project settings' help box has broken links

### ISSUE THREAD

**Issue by fungiboletus** [drone/drone-ui#307]
![image](https://user-images.githubusercontent.com/45740/64415063-dcd20780-d094-11e9-8299-b537b4562b03.png)

The project settings help box has broken links:

 * https://docs.drone.io/user-guide/signature/
 * https://docs.drone.io/administration/user/admins/

It's also showing help about trusted repositories even for non admin users.

By the way it's very difficult to find out that some users can be admins and how to make them admins.

**Comment by bradrydzewski** [comment]
fixed by 2c8cc40a39bdb8d280b08ac11392fc15e210fd9b
