### ISSUE TITLE
How 'dist/go_dist.go' is compiled?

### ISSUE THREAD

**Issue by harshzalavadiya** [drone/drone-ui#308]
As vue cli only generates static files but how it's being placed in go file for serving?

**Comment by tboerger** [comment]
You can do that only if you got go as well as bradrydzewski/togo installed, after that you can just execute go generate: https://github.com/drone/drone-ui/blob/vue/dist/dist.go

**Comment by harshzalavadiya** [comment]
Great,
Thanks
