### ISSUE TITLE
Text goes outside the log box

### ISSUE THREAD

**Issue by GCorbel** [drone/drone-ui#309]
With some steps, the text goes outside the box in logs as you can see here : 

![image](https://user-images.githubusercontent.com/1296201/64617375-5a0abe80-d3ac-11e9-9fd7-a5c93c0fca58.png)

It's written white on white so we have to change for the full screen view or download logs.

**Comment by bradrydzewski** [comment]
fixed by dc6cbfb66b3b4449eabd76a7431150a8d7de4895. Updated distribution will be included in the 1.5 release of Drone.
