### ISSUE TITLE
Search window is not closed after search

### ISSUE THREAD

**Issue by xoxys** [drone/drone-ui#310]
The search bar and it's overlay is not closed after entering a search value and enter a search entry. Looks like:

![grafik](https://user-images.githubusercontent.com/3391958/65134578-ca48be00-da04-11e9-9706-01cefac4c07c.png)
~~Seems like a Firefox issue, works without issues on Chrome/Safari.~~

**Comment by tboerger** [comment]
I have checked that on Firefox on macOS, if you use the search and you *click* on the resut this behavior is as described above, using the arrow keys and pressing enter works totally fine.

So somehow the click event is not handled properly.

**Comment by bradrydzewski** [comment]
duplicate of https://github.com/drone/drone-ui/issues/310

**Comment by tboerger** [comment]
@bradrydzewski duplicate of what? Your text refers to this issue :D

**Comment by bradrydzewski** [comment]
sorry, meant to say https://github.com/drone/drone-ui/issues/263
