### ISSUE TITLE
remove cdn dependency

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#32]
moving the suggestion from pull request #31 to its own issue

> Why serving all assets directly and not from CDN? I suggest that many will run their CI in corporate environments. IMHO having the plus in privacy by not needing to request content from third parties outweights the small chance, to already have a certain file somewhere in cache. And even if not, since all assets have hashes and so can be long term cached, this is at most a concern for the very first visit of the UI.

**Comment by bradrydzewski** [comment]
fixed in master

**Comment by jacksgt** [comment]
Great stuff, thanks for implementing this! 🥇

**Comment by sbruder** [comment]
In the latest version of drone, Roboto Mono and Open Sans are loaded from Google Fonts. Is there any reason you started using a CDN for that again?
