### ISSUE TITLE
Wrong link to gitea tags

### ISSUE THREAD

**Issue by nicoulaj** [drone/drone-ui#320]
Using drone with Gitea, on tag builds, the drone web UI shows a link to the tag that redirects to this URL:
```
{gitea URL}/{repo}/tag/{tag}
```
But the proper URL for gitea is:
```
{gitea URL}/{repo}/src/tag/{tag}
```

**Comment by bradrydzewski** [comment]
the gitea urls are generated server-side.  this was fixed by [this patch](https://github.com/drone/go-scm/pull/52).
