### ISSUE TITLE
Empty feed results in error

### ISSUE THREAD

**Issue by tboerger** [drone/drone-ui#34]
While loading an instance with en empty feed I'm getting `app.js:7Uncaught TypeError: Cannot read property 'sort' of null` because the API returns `null` while the UI expects an object.

**Comment by bradrydzewski** [comment]
this probably could be changed at the server level at:
https://github.com/drone/drone/blob/master/store/datastore/users.go#L49
https://github.com/drone/drone/blob/master/store/datastore/users.go#L30

we could initialize the list so that an `[]` is always returned instead of a `nil`

```diff
-feed []*model.Feed
+feed = []*model.Feed{}
```

**Comment by tboerger** [comment]
I can create a PR if those are the only places.

**Comment by bradrydzewski** [comment]
sounds good!  and yes, once we merge the PR drone will grab the updated js code with the csrf fix :)

**Comment by tboerger** [comment]
Will be solved via https://github.com/drone/drone/pull/1707

**Comment by bradrydzewski** [comment]
ok should be good
