### ISSUE TITLE
New UI constantly disconnects.

### ISSUE THREAD

**Issue by dessalines** [drone/drone-ui#352]
On the new UI that's deployed to cloud.drone.io, the UI disconnects at random, so I have to frequently refresh the page to know the actual current build step. Loading indicators will circle forever, when in actuality its long since completed that step.

My guess is if you're using websockets, its not a proper reconnecting-websocket.

**Comment by bradrydzewski** [comment]
we are not using websockets, we are using SSE which automatically re-connect.  I have not personally experienced any issues with connections constantly dropping, so please provide more details that might help us better understand the problem you are experiencing.

**Comment by dessalines** [comment]
I have 2 tabs open that are disconnected now. When I try to click on anything on the page, I get this in the XHR response:

```
XHRGEThttps://cloud.drone.io/api/stream/LemmyNet/lemmy/640/1/2
[HTTP/2 200 OK 68ms]
    : ping
    event: error
    data: eof
   ```

I'm not very knowledgeable on SSR so I don't know how it handles reconnects, but with websocket, its generally a good practice to refetch all data on reconnect. That doesn't seem like its being done here, else the loading indicators would update.

**Comment by bradrydzewski** [comment]
In the above snippet you are connecting to a log stream.  It is normal for log streams to connect and disconnect when the log completes.  The EOF indicates the end of the log stream which is normal behavior.  Perhaps there is additional context you can provide, because this otherwise seems normal.

**Comment by dessalines** [comment]
How are you handling data fetching on SSE reconnects?

**Comment by darkguy2008** [comment]
I was about to open a new bug but I came across this one when experiencing the same issue.

![image](https://user-images.githubusercontent.com/6304136/112783247-246c0b80-900c-11eb-9f85-a1a3b43304c1.png)

It's all good with your SSEs (first time I see them, so the EventStream tab was new to me in Chrome). However, notice how my job evidently fails but the UI is still stuck at "Step is running"... If I refresh the page, then it shows as build failed.

The new UI look and feel rocks, but there's some room for improvements for things that used to work.

I'll also take the chance to see if there's a possibility to permanently enable autoscroll on log view.

Also, is there any way to go back to the old UI?

Thanks!

**Comment by microadam** [comment]
Having the same issue as well. Just curious if this has been acknowledged as a genuine problem, or if it could be down to individual setup? (reverse proxy possibly needing configuring better for handling SSE or some such)

**Comment by darkguy2008** [comment]
@bradrydzewski do you have any idea about the issue I'm reporting with the screenshot above? This issue seems to be ongoing with no real solution as of yet. Thanks.

**Comment by microadam** [comment]
Fixed for me since https://github.com/drone/drone-ui/commit/5f47342ade8cabe5574e4b56efe2c7a2fc499439

**Comment by tphoney** [comment]
This is no longer an issue, thanks for raising it.
