### ISSUE TITLE
UI crashes when no builds are found

### ISSUE THREAD

**Issue by chivay** [drone/drone-ui#364]
Function `getSummaryMeta` in `src/pages/builds/summary/summary.jsx ` assumes that a build exists, which breaks the whole app in case none is found.

https://github.com/drone/drone-ui/blob/275452705725be3e8a9fc5e11c707d03de1cb81f/src/pages/builds/summary/summary.jsx#L21-L22

**Comment by d1wilko** [comment]
Hi @chivay can you explain the scenario in which you found this bug?

The reason I ask is that if there are no builds then the Summary component should not render at all.

https://github.com/drone/drone-ui/blob/275452705725be3e8a9fc5e11c707d03de1cb81f/src/pages/builds/builds.jsx#L62-L66

these lines should run instead.

**Comment by chivay** [comment]
I was just trying to set up latest Drone version ;)
After debugging it for a while, I think the problem is actually here:

https://github.com/drone/drone-ui/blob/275452705725be3e8a9fc5e11c707d03de1cb81f/src/pages/builds/summary/summary.jsx#L61

It is possible that no build matches the filter and `barData` becomes an empty array.

**Comment by d1wilko** [comment]
hey @chivay this should be fixed now - thanks for your debugging :)

**Comment by chivay** [comment]
Cool, thanks!
