### ISSUE TITLE
Use more functional coding style

### ISSUE THREAD

**Issue by choffmeister** [drone/drone-ui#38]
There are places with code like

``` js
let terms = [];

for (var prop in this.state.groups) {
  terms.push(
    <Term key={prop} name={prop}
      lines={this.state.groups[prop].lines}></Term>
  );
}
```

This is very imperative coding style which could be written more functional like so:

``` js
// this could also be simpler when using lodash or similar to iterate over objects
const terms = Object.keys(this.state.groups)
  .map((key) => ({key, group: this.state.groups[key]}))
  .map(({key, group}) =>
    <Term
      key={key}
      name={key}
      lines={group.lines}/>
)
```

Main advantage is the lack of state mutation and hence easier to reason about code (and often short and less error prone, even though in this particular example with iterating over an object the code is longer).

Are these kind of code style "improvements" wanted? Then I would create PR(s) for that.

**Comment by bradrydzewski** [comment]
I fully agree with this issue, but am going to close since it is a bit broad. I encourage pull requests that use a more functional coding style, as well as creating github issues for specific sections of code that need to be improved.
