### ISSUE TITLE
Error when opening build

### ISSUE THREAD

**Issue by julienduchesne** [drone/drone-ui#382]
I upgraded from 2.2.0 to 2.3.1 (Drone version, not UI version) today and I'm getting this error when trying to view a build:
![image](https://user-images.githubusercontent.com/29210090/133137004-bc238551-ffcb-4aed-9b5d-96d71601b625.png)

I believe it worked before I tried to start a new build from the repository page. It said `New build has started successfully`, but nothing really happened (no new build) and now I can't open the last two builds

**Comment by d1wilko** [comment]
Hi @julienduchesne I'm trying to recreate this issue in v2.3.1 but its working as expected for me.

Can you provide steps for me to reproduce? was it a newly activated repo? any info you can provide would be appreciated :)

**Comment by julienduchesne** [comment]
It's actually every build that has stages that were cancelled before being scheduled to a runner that fails. Related to this https://github.com/drone/drone-ui/pull/376?

**Comment by d1wilko** [comment]
@julienduchesne thanks I can now recreate.

Yep thats the problem PR :) I've merged a fix now (https://github.com/drone/drone-ui/pull/383) and will get it released soon!

Thanks for your help!

**Comment by d1wilko** [comment]
This is fixed as of drone v2.4.0 :)
