### ISSUE TITLE
ReferenceError: Can't find variable ResizeObserver

### ISSUE THREAD

**Issue by glaszig** [drone/drone-ui#394]
https://github.com/drone/drone-ui/blob/639a5bd50e4bb115e47de4e991e74121bf784ccb/src/hooks/use-resize-observer.js#L19

would you accept a pr that adds a shim for older but still used browsers (Safari 12.1.2)?

**Comment by d1wilko** [comment]
Hi @glaszig, I've had a look at the market share of safari versions earlier than 13.1 (when ResizeObserver support was introduced) - its roughly 0.2% (as per https://caniuse.com/usage-table) - I'd prefer not to introduce a shim for such a small share.

Sorry, but thank you for the suggestion :)
