### ISSUE TITLE
Menu popup window leaves traces of itself on second click

### ISSUE THREAD

**Issue by strk** [drone/drone-ui#45]
[ moved from https://github.com/drone/drone/issues/1711 ]

To reproduce, on Firefox 47.0 for Linux:

    Go to project page as an authenticated user
    Click on the 3 vertical dots on the upper-right corner (a menu pops up)
    Click again on the same 3 vertical dots (the menu text disappears but the border remains)

Here's a screenshot of the leftover:
![screenshot-drone-menu-leftover](https://cloud.githubusercontent.com/assets/289678/16775677/1b2ef6d2-4862-11e6-8085-ba40b58b0494.png)

**Comment by strk** [comment]
Seems to be an upstream bug as I can also reproduce here:
https://getmdl.io/components/index.html#menus-section

See screenshot:
![getmdl_bug](https://cloud.githubusercontent.com/assets/289678/16775871/0c8d6658-4863-11e6-8941-e6ecafc8d637.png)

**Comment by strk** [comment]
Filed upstream as https://github.com/google/material-design-lite/issues/4549

**Comment by bradrydzewski** [comment]
tracking under official mdl issue
