### ISSUE TITLE
Scroll to top when switching pages

### ISSUE THREAD

**Issue by KyleOndy** [drone/drone-ui#48]
Sorry about the long title, I couldn't figure how to say it any more tersely.

If you are following a build and the build is long enough to scroll the page, when you navigate back to the list of the repositories past builds (on left), I expect to be shown the top of the list (most recent builds), however I get left scrolled down the page.

This requires me to scroll to the top to see by most recent build status.

**Comment by bradrydzewski** [comment]
fixed in master

**Comment by oscarlofwenhamn** [comment]
This appears to be an issue again in Drone v1, not sure if this issue should be reopened or if a new one should be opened.
