### ISSUE TITLE
Handle newlines correctly in build logs

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-ui#49]
newlines aren't handled correctly in two different sections of the code. First it seems that newlines aren't being properly escaped in our tracing code.

the desired output for `echo /n/n/n` would be `+ echo /n/n/n`. The actual output is `+ echo`. I believe we need to properly escape the `\n` with `\\n` so that is is properly traced.

the second issue is that we omit empty strings in the JSON log output. As a result I'm guessing we are skipping over these lines in the logs because the `out` text parameter is undefined. We need to not do this ...

<img width="334" alt="screen shot 2016-08-11 at 4 02 09 pm" src="https://cloud.githubusercontent.com/assets/817538/17607809/fc5a8194-5fdc-11e6-9345-c468b3c58406.png">

this manifests in the user interface as a bunch of missing lines in the output, instead of empty rows as one would expect:

<img width="289" alt="screen shot 2016-08-11 at 4 03 22 pm" src="https://cloud.githubusercontent.com/assets/817538/17607832/357cafa6-5fdd-11e6-9a96-a29eef12783c.png">

**Comment by 7heo** [comment]
For now, there is a workaround: using `echo " "` for each newline, with the space between the double quotes being a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space).

**Comment by bradrydzewski** [comment]
this is now fixed in master
