### ISSUE TITLE
Extract API paths to separate file

### ISSUE THREAD

**Issue by metalmatze** [drone/drone-ui#5]
I think it would be helpful to separate all URI paths to a separate file.
That way they can be imported by files that need them and they're in one place.

**Comment by MetalMatze** [comment]
I think it would be helpful to separate all URI paths to a separate file.
That way they can be imported by files that need them and they're in one place.

**Comment by choffmeister** [comment]
I don't think that exporting the URI is really a good idea. In a flux style application the only global interaction with data is dispatching store actions. I guess this remains true for the baobab library. So if a component wants to interact with the drone API, it should interact with it via baobab, not by HTTP calls directly.

**Comment by tboerger** [comment]
And don't forget the possibility to inject a root path somehow :D

**Comment by bradrydzewski** [comment]
closing since we have encapsulated all drone logic in a separate [drone.js](https://github.com/drone/drone-ui/blob/master/src/drone/actions/drone.js) library, and will be moving to a separate repository.
