### ISSUE TITLE
Show only current step & current step task during build

### ISSUE THREAD

**Issue by carldanley** [drone/drone-ui#50]
It would be nice to only present the relevant data to a user when viewing the logs for a particular build; ie - only show each step during the build process. If you wanted to take it even farther, minimize each task in each step of the build; thus, only showing the current task being run. This allows us to drill down into each part of the build where we need to.

Here is a screenshot for what I'm trying to convey:

![drone-idea](https://cloud.githubusercontent.com/assets/1470571/17907628/d1a3c204-694a-11e6-8227-6c96197c76f5.jpg)

Note:
- After a "step" finishes, it would auto-close.
- After a "task" in a "step" finishes, it would auto-close; the "+" icon would allow you to expand that task and view the output from it, etc.

In the event of a failed build, this would allow us to have a better view of what step it failed on and specifically what task in that step.

Just an idea I had and wanted to submit it somewhere as I thought it may useful to someone else. This issue would correspond directly to the following issues as well:
1. https://github.com/drone/drone-ui/issues/48
2. https://github.com/drone/drone-ui/issues/30

**Comment by bradrydzewski** [comment]
this has been resolved with a layout change. We now display the active process list in the right pane with the ability to toggle outputs. As a result the folding (or auto-folding) in this case is no longer required.

<img width="1054" alt="screen shot 2017-07-17 at 12 39 32 am" src="https://user-images.githubusercontent.com/817538/28255685-33d49ad6-6a88-11e7-821a-a51106f0a109.png">
