### ISSUE TITLE
Cannot Access Build List from Mobile Web Browser

### ISSUE THREAD

**Issue by dvmorris** [drone/drone-ui#52]
When I load drone on a mobile browser, the build list sidebar is collapsed, so I cannot access any builds.

![image](https://cloud.githubusercontent.com/assets/186253/18297357/9387d074-7475-11e6-917f-b22b3dd87066.png)

**Comment by dvmorris** [comment]
https://github.com/drone/drone-ui/pull/58

**Comment by bradrydzewski** [comment]
merging with issue #27
