### ISSUE TITLE
Chaning any settings for gitlab repo gives error

### ISSUE THREAD

**Issue by bonanza123** [drone/drone-ui#56]
I just installed drone server and agent with version 0.5 (from docker) and linked by own gitlab repo with it (it has version 8.10.1).  I also successfully created the the drone account linking to my gitlab account. But whenever I want to change anything in the drone settings for some of the gitlab repos (like "Push Hooks") I just get a pop-up message showing `Error updating repository settings`.

As I run the agent and server in DEBUG mode,  i pulled the latest logs but there is no information about that.

**Comment by bradrydzewski** [comment]
please use our developer channel for support questions https://gitter.im/drone/drone
