### ISSUE TITLE
Poll for changes of data by currently shown page

### ISSUE THREAD

**Issue by MetalMatze** [drone/drone-ui#6]
It should be pretty simple to add polling for data of the current page.
When the initial data fetching is done and the `componentDidMount` there could be an `setInterval` to fetch new data periodically.
The only thing to keep in mind is to remove those intervals, once the page unmounts.

**Comment by tboerger** [comment]
Maybe it makes sense to add another server sent event to push changes?

**Comment by MetalMatze** [comment]
@tboerger Yes, that would be a great feature. Yet I'd say to wait for the next release and to simply use polling for now, because it would require a lot of changes to the server and the client.

**Comment by bradrydzewski** [comment]
this is now implemented via websocket
