### ISSUE TITLE
build history filtering

### ISSUE THREAD

**Issue by marcinc** [drone/drone-ui#63]
Currently there is nothing in UI which enables the user to filter the build history. 
I'd like to propose that filtering by basic build item properties is added to the UI so that it's easier to find relevant items. Initially filtering by `branch`, `author`, `event`, `tag`, `status`, `deploy_to`  should be sufficient but could be extended to include any build item attribute.

Some general top level ideas:
- Filtering criteria will be provided via tags e.g. `status:success`
- It should be possible to chain tags to build more complex filtering criteria, for example: `author:foo` `status:failure` ...
- It should be possible to add multiple filter components of the same attribute e.g. `tag:v1` `tag:v2`
- It should be easy to add and remove individual components from the filter criteria.
- All filter criteria components will be applied with logical AND operator, i.e. all conditions need to be met for the build history item to show up in the list. 
- Filter tag auto-completion (NTH)

**Comment by tboerger** [comment]
Sounds interesting and somebody already talked about that on gitter

**Comment by marcinc** [comment]
@tboerger yes, @vaijab mentioned that on gitter as we're looking into adding that. Am currently working on a prototype of that enhancement as it's something we'd like to use.

**Comment by marcinc** [comment]
I've opened #64 with initial working version of build history filtering. Would be great to get some feedback on that. We've started using it internally and it's been quite useful. One extra addition to original proposal was the ability to pass filter in the query string so that it can be shared e.g.: 
`?filter=status:success;event:deployment`

**Comment by bradrydzewski** [comment]
merged #64

**Comment by strk** [comment]
@bradrydzewski was this support removed ? I tried this w/out success:
https://cloud.drone.io/postgis/postgis?filter=status%3Asuccess
