### ISSUE TITLE
Enhacement: Add ability to modify build's custom params

### ISSUE THREAD

**Issue by marcinc** [drone/drone-ui#66]
Currently UI doesn't allow modification to build's custom parameters introduced in https://github.com/drone/drone/pull/1735, however it already displays them in the build pane. 
Addition of a simple form to allow alteration of those parameters would enable users to restart the build with modified params.

**Comment by bradrydzewski** [comment]
I think there are a few different things we'll want to consider in addition to parameters, for example, the ability to restart vs fork, and the ability to execute as a deploy event with a deployment environment specified.

**Comment by marcinc** [comment]
Regarding https://github.com/drone/drone-ui/pull/69#issuecomment-260972548 I agree. This will initially allow to choose between (simple) restart, restart with params. I'm going to replace the simple RESTART button (see screenshot below) with a split one and move build variables form there. 
![screen shot 2016-11-28 at 11 09 19](https://cloud.githubusercontent.com/assets/28119/20666418/02e780e6-b55c-11e6-9321-e873725bc9dc.png)

**Comment by bradrydzewski** [comment]
@marcinc the material design library doesn't have a split button (with ripple effect, etc) but we can emulate this by using two buttons:

```
<button className="button-follow">Follow</button>
<button className="button-follow"><i class="material-icons">more_horiz</i></button>
```

and then use css to make them look like a split button by removing the margin between the two and adjusting the border-radiuses:

```
.button-follow {
    margin-right: 0px;
    border-top-right-radius: 0px;
    border-bottom-right-radius: 0px;
}
.button-follow-more {
    border-top-left-radius: 0px;
    border-bottom-left-radius: 0px;
}
```
