### ISSUE TITLE
Enhancement: Expose a href to parent build in the UI.

### ISSUE THREAD

**Issue by marcinc** [drone/drone-ui#68]
Since a reference to a parent build on forks / deploys is now persisted it could be surfaced in the UI. I guess the good place to place a link to the parent build would be somewhere in the build pane. 

Build list itself could indicate that a build has a parent too, for example by displaying parent build number next to its own build number e.g. `#16 < #15` or similar?

Related: https://github.com/drone/drone/issues/1818, https://github.com/drone/drone/pull/1823.

**Comment by marcinc** [comment]
Build list indicating that a build has a parent:
![screen shot 2016-11-11 at 12 48 45](https://cloud.githubusercontent.com/assets/28119/20215634/865ae76c-a80d-11e6-8702-8d1847a84f8f.png)

Build pane with reference link to a parent build:
![screen shot 2016-11-11 at 12 42 42](https://cloud.githubusercontent.com/assets/28119/20215646/af0bcc08-a80d-11e6-8c28-46f0322df27a.png)

**Comment by bradrydzewski** [comment]
Looks good !

**Comment by tboerger** [comment]
Should this be solved via #70?

**Comment by bradrydzewski** [comment]
@tboerger yes good catch, thanks! closing
