### ISSUE TITLE
Consider replacing "Roboto Mono" with another monospace font

### ISSUE THREAD

**Issue by jhasse** [drone/drone-ui#74]
Roboto Mono has a bug in Firefox: Bold characters don't have the same weight as normal characters. This messes up some formatting in our build output.

As the default monospace fonts are pretty good on most systems, would you consider changing the `@font-family-mono` to simply `monospace`? This would also decrease the download size for the UI, as it is one web font less :)

**Comment by jhasse** [comment]
Could you elaborate why you closed this?

**Comment by bradrydzewski** [comment]
This has been fixed in the latest UI refresh. We are using `Roboto+Mono:300,400,500` with `500` for bold fonts. I have confirmed that everything renders correctly in the latest version of Firefox.

**Comment by jhasse** [comment]
Ah ic! Thank you :)

**Comment by jhasse** [comment]
Unfortunately it isn't working for me:

![bildschirmfoto von 2018-11-30 10-40-20](https://user-images.githubusercontent.com/80071/49281281-762c1780-f48c-11e8-9c27-4980df15992a.png)

Firefox 63.0.1 on Linux.

**Comment by jhasse** [comment]
Also happening on Windows 10 with Firefox 64.0.
