### ISSUE TITLE
Link build steps and lines

### ISSUE THREAD

**Issue by tuxity** [drone/drone-ui#78]
I was wondering if it's possible to add a link on build steps and line(s) in build steps playing with anchors like this:
http://beta.drone.io/drone/drone/831#mysql
http://beta.drone.io/drone/drone/831#mysqlL56

When you want to send a build error to a coworker it could be very nice

**Comment by MasseGuillaume** [comment]
It look like this is where we should add this: 

Term Row is a build line
https://github.com/drone/drone-ui/blob/0b8d4724dfe41e17c65053c6e76cf5020decd62c/src/components/term_row.js#L9

This is the router
https://github.com/drone/drone-ui/blob/0b8d4724dfe41e17c65053c6e76cf5020decd62c/src/routes.js#L6

**Comment by kdnutrien** [comment]
This would be really useful.  Circle and Travis support this.
