### ISSUE TITLE
Prompt user when deactivating a repo

### ISSUE THREAD

**Issue by jmccann** [drone/drone-ui#79]
We have had people "accidentally" deactivate repos.

For me this is usually due to a person being one of multiple Admins to a repo and not understanding Drone as well as others.  They want to "cleanup" their Drone UI and think untoggling a repo impacts only them and their UI view.

Would like a prompt to a user for confirmation when deactivating a repo.  With a message such as:

> Are you sure you want to deactivate <repo>?  This will prevent future builds from occurring as well as delete any web hooks, secrets and build logs for <repo>.

**Comment by bradrydzewski** [comment]
@jmccann sorry for the delay here. The reason I haven't moved forward with this is that I've been kicking around this design change https://github.com/drone/drone/issues/2036

**Comment by bradrydzewski** [comment]
ok, sorry for the delay on this. In master when you de-activate a repository it now toggle a `repo_active` flag in the database instead of deleting the repository 😄

**Comment by tonglil** [comment]
@bradrydzewski is there a way to delete the repository via the UI still? Or must be done via CLI?

**Comment by tboerger** [comment]
I thought the same because i wanted to entirely reset a project :)

**Comment by tonglil** [comment]
^same use case

**Comment by bradrydzewski** [comment]
We do have an endpoint that will delete the repository from the database. You could curl the endpoint as a temporary solution, in the meantime we should get it added to the CLI for our next release.

```
DELETE /api/repos/{owner}/{repo}?remove=true
```
