### ISSUE TITLE
Set CDN package versions from package.json

### ISSUE THREAD

**Issue by MetalMatze** [drone/drone-ui#8]
It would be good to have the CDN versions in index.html in sync with the package.json version.

**Comment by tboerger** [comment]
And please add a switch to be able to use only local versions instead of CDN versions.

**Comment by MetalMatze** [comment]
@tboerger That would be nice indeed. Also there needs to be a ENV to use .js or .min.js. But I think that's something to add after it's merged into drone/drone

**Comment by bradrydzewski** [comment]
let's combine this with https://github.com/drone/drone-ui/issues/32

**Comment by choffmeister** [comment]
Yeah, as far as I see all this stuff will come automatically as soon as #32 is merged.
