### ISSUE TITLE
button to jump to bottom of logs

### ISSUE THREAD

**Issue by jhasse** [drone/drone-ui#84]
IMHO this would make sense. ATM the button does nothing when a build is finished.

**Comment by patrickjahns** [comment]
Maybe it would be better to disable the button after a finished build? Or provide a different naming since it is not about "follow" anymore

**Comment by bradrydzewski** [comment]
the "follow" button is a toggle button, that you can toggle on an off. I personally like that I can toggle "follow" before I hit the restart button. So my vote is to not change the follow button, and instead add an additional "scroll to bottom" button

**Comment by jhasse** [comment]
> I personally like that I can toggle "follow" before I hit the restart button.

Couldn't you also click restart and then follow to achieve the same result?

**Comment by bradrydzewski** [comment]
sometimes I don't want it to follow, so I un-toggle follow before hitting restart. The toggle button state is stored globally so that it remembers your prior choice.

**Comment by jhasse** [comment]
Ah good point.

My use case is that I always want it to "follow" (see the end of the build output), since that's usually where the errors are displayed. That's something I want *especially* when a build has failed (finished), so I would expect the UI to jump to the button when I open a build and the global follow state is true (regardless if the build has finished or not).

**Comment by bradrydzewski** [comment]
fixed by https://github.com/drone/drone-ui/commit/463e52c2c4eafd77fe4156daf479f5119587d257
