### ISSUE TITLE
Yes!

### ISSUE THREAD

**Issue by vespakoen** [drone/drone-ui#9]
Hey! This is awesome!

I am a JavaScript developer by profession and I have been looking for ways to help out on drone.

This would allow me to contribute, and I think a lot of others will too.

I prefer this much more than polymer.

I saw you made some changes on your own branch (with polymer), I suppose this continues on that work? What I am trying to ask is, for this to work I will probably need to use your branch that has some extra websocket endpoints I believe?

Just my 2 cents.

**Comment by bradrydzewski** [comment]
this new frontend is being merged into master `drone/drone` later today
