### ISSUE TITLE
YAML cmmand underscores are being replaced by slashes

### ISSUE THREAD

**Issue by olymk2** [drone/drone-ui#91]
Running a job with =drone exec --repo.trusted= works perfectly, however when i deploy to the drone server _ in my commnds are replaced by / do i need t do some kind of escaping.

If not I will take a look if i get some time if you have any ideas / pointers on where to look.
```
phpunit --log-junit /drone/src/phpunit-docker.xml "/drone/src/Tests/phpunit/INITIAITE_TEST_FEED.php"
```
translates to this
```
Cannot open file "/drone/src/Tests/phpunit/INITIAITE/TEST/FEED.php"
```

**Comment by jhasse** [comment]
Looks like an issue with drone itself, you might consider opening an issue here: https://github.com/drone/drone
