### ISSUE TITLE
When copying the stack trace, the line numbers and time value are also copied.

### ISSUE THREAD

**Issue by ahatzz11** [drone/drone-ui#98]
Here's an example:

```
+ git init
0s
2
Initialized empty Git repository in /drone/src/[domain]/[org]/[repo]/.git/
0s
3
+ git remote add origin https://[domain/[org]/[repo].git
0s
4
+ git fetch --no-tags origin +refs/pull/17/merge:
```

The line numbers from the left and the time from the right are added, making copy/pasting from drone kinda messy.

**Comment by jhasse** [comment]
This works for me. What browser are you using?

**Comment by ahatzz11** [comment]
Chrome - Version 57.0.2987.133 (64-bit)

**Comment by jhasse** [comment]
Oh you're right, I was using Firefox.

This is a bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=147490

**Comment by bradrydzewski** [comment]
closing since it is a chrome bug
